### PR TITLE
temperature@fevimu: Added setting to reduce precision

### PR DESCRIPTION
**Pull request by leplastic**
Hi, I created a setting to reduce the precision of the temperature. In my case, I found the value always changing a bit distractive. With this setting, only the integer part of the value is show for both Celsius and Fahrenheit (28 instead of 28.5).

I labeled the setting as "Show only integer part of temperature". I feel it is a bit geekish for public in general. I'm accepting better suggestions for this if the change is accepted.

@fevimu @NikoKrause

### CODE REVIEW

**Comment by NikoKrause** [comment]
It can be merged. Maybe you can say `Round temperature to integer`?
Not sure either. Let me know if you want to change it or leave it.

Also can you do me a favor? Can you add those lines, which are suggested here into your pull request? https://github.com/linuxmint/cinnamon-spices-applets/issues/1502

**Comment by NikoKrause** [comment]
Or maybe
```
Use integer values ​​for temperature
```

**Comment by leplastic** [comment]
I followed your last suggestion, which sounds better. I also added the lines from #1502 PR and the popup now closes when clicking somewhere else.

**Comment by NikoKrause** [comment]
Thank you very much.
Also thanks for @germanfr for the autoclose of the popup menu.

**Pull request merged**
