### PR TITLE
timer-notifications@markbokil.com: Add translation support

### PR DESCRIPTION
**Pull request by eson57**
Add translation support, .pot translation template and Swedish translation.

### CODE REVIEW

**Comment by NikoKrause** [comment]
Thanks for translating applets. Plesse get used to add the applets uuid in the commit messages as well, like you did in the pull request title. I'll make a squash merge for now.

**Comment by NikoKrause** [comment]
ping @mbokil

**Comment by eson57** [comment]
Ok, I'll try to remember.

**Comment by NikoKrause** [comment]
Why die you closed this? I can squash merge it.

**Comment by eson57** [comment]
Sorry, I'm new to this. Trying to learn. It seemed to give me problem when wanting to PR another applet, because they are all in the same repository.
Well, I can make another PR... with proper commit messages.

**Comment by collinss** [comment]
@eson57 Are you using separate branches for your pr's? That will help if you do.

**Comment by eson57** [comment]
I did, but they where somehow merged. I have no idea what happened.
Any way, I think I'm done now. The applets that I use, all have Swedish translations. ;)

**Comment by Odyseus** [comment]
Hello, everybody.

@eson57: You must have created the new branch or branches from the branch you were in and not from **master**. This happened to me once. Do a `git checkout master` every time you want to create a new branch. Just in case you don't know, `git branch -v` lists all your branches. The one highlighted (in green for me) is the currently checked out branch.

**Comment by eson57** [comment]
Thanks for sorting that out, @Odyseus  👍

**Pull request closed without merging**
