### PR TITLE
Added DGS applet files

### PR DESCRIPTION
**Pull request by bpivaty**
Initial DGS applet files

### CODE REVIEW

**Comment by jaszhix** [comment]
Hi, the [file structure](https://github.com/linuxmint/cinnamon-spices-applets#file-structure) needs to be ```UUID/files/UUID/```, so the extension can be extracted into a directory with the UUID as its name.

I noticed this warning:

```
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/dgs-bpivaty@gmail.com/applet.js line 44]: reference to undefined property this.myId
```

I think its because object properties can't be initialized without assignment, like variables can.

**Comment by bpivaty** [comment]
Hi,
Thank you going to fix.

**Comment by bpivaty** [comment]
Sorry for this way but I am new with git, I always used clearcase at work, and also this is my first javascript work ever. Will read learn more about git to improve.

**Comment by jaszhix** [comment]
No problem, looks good to me.

**Comment by bpivaty** [comment]
I think I just forgot to provide an icon at the top level right?

**Comment by jaszhix** [comment]
Yeah, just add it to the top level in ```dgs-bpivaty@gmail.com/``` as icon.png. It also should have square dimensions.

**Comment by bpivaty** [comment]
Done. Thanks for your help. I am very happy. Very long I didn't do anything
for the community

**Comment by bpivaty** [comment]
Hi Jason. There is a little issue and I don't know how to fix it .
notifier.js and user.js must be executable.
I checked on internet but don't know how to do it on git.

**Comment by jaszhix** [comment]
You just need to set them with the correct permission (`chmod +x`) before committing them.

**Comment by bpivaty** [comment]
That strange they were +x. All was working locally. Ok going to do it againSent from Nylas Mail, the best free email app for work
          
            
            On Sep 10 2017, at 8:45 pm, Jason Hicks <notifications@github.com> wrote:
            
            
              You just need to set them with the correct permission (chmod +x) before committing them.

**Comment by jaszhix** [comment]
Actually, the permission may be lost since they're getting archived. Try prepending the commands launching them with `cjs`.

**Comment by bpivaty** [comment]
Done. Thanks for your help again

**Pull request merged**
