### PR TITLE
radio@driglu4it update

### PR DESCRIPTION
**Pull request by Driglu4it**
Now we can include or exclude station of list and control volume by mousewheel on icon of applet

### CODE REVIEW

**Comment by NikoKrause** [comment]
?
This PR just removes one whitespace

**Comment by Driglu4it** [comment]
Sorry, i have update now )

**Comment by NikoKrause** [comment]
The PR hasn't changed at all.
You opened a bunch of PR for the same applet, each changing 1 file only.
If it's the same applet, you can add the changes in one PR only, not 5-6 PR for each file.

**Comment by Driglu4it** [comment]
I added all the changes.
sorry, I do not know how to work with github

**Comment by NikoKrause** [comment]
A tutorial: https://github.com/NikoKrause/CinnVIIStarkMenu/issues/28

**Comment by jaszhix** [comment]
Can you condense these 5 PRs into one PR? You just need to create one branch/PR per applet.

**Comment by jaszhix** [comment]
Closing PRs since I'm not sure what's going on with these.

**Pull request closed without merging**
