### PR TITLE
weather@mockturtl Update 3.1.3

### PR DESCRIPTION
**Pull request by Gr3q**
Changes:

- [x]  Update DarkSky API cutoff date
- [x] Update TS declarations
- [x] Resolves https://github.com/linuxmint/cinnamon-spices-applets/issues/3926  Change Climacell naming to Tomorrow.io

### CODE REVIEW

**Comment by jorgenqv** [comment]
Idea: The screenshot for the applet on the spices website feels a bit pale and old. Did not figure out how to make a pull request for updating a image/binary so I simply put a suggestion for a new screenshot here in this comment :-)
weather@mockturtl spices website screenshot update 2021-09-19

**Comment by jorgenqv** [comment]
@Gr3q Looks like the screenshot is not updated from github.com to the spices website, it's still the old one. 
Do we need to do something else?
https://cinnamon-spices.linuxmint.com/git/applets/weather@mockturtl/screenshot.png
https://raw.githubusercontent.com/linuxmint/cinnamon-spices-applets/master/weather%40mockturtl/screenshot.png
Thanks!

**Comment by Gr3q** [comment]
It does show up now.

**Comment by jorgenqv** [comment]
> It does show up now.

Yes for me too, thanks!

**Pull request merged**
