### PR TITLE
Add Chinese translation for Time Out

### PR DESCRIPTION
**Pull request by giwhub**
Time Out @narutrey: Create zh_CN.po.

### CODE REVIEW

**Comment by NaruTrey** [comment]
I approve.

**Comment by NikoKrause** [comment]
screenshot-area-2017-03-13-103705
The COMMIT-MESSAGES (red rectangle) should look like this `UUID: Create zh_CN.po`
In this case `timeout@narutrey: Create zh_CN.po`

**Comment by giwhub** [comment]
Thanks,how to change that COMMIT-MESSAGES (red rectangle) ?

**Comment by NikoKrause** [comment]
This one can go wrong, if you never done this before. So make a backup, before trying.

To change the last commit message:
`git commit --ammend -m "New and correct message" `
Then
`git push -f`

**Pull request merged**
