### PR TITLE
weather@mocturtl - 2.0.0 Update: Rework to support other APIs after Yahoo API closes

### PR DESCRIPTION
**Pull request by Gr3q**
Pull request to make the weather applet functional again.
Issue link: https://github.com/linuxmint/cinnamon-spices-applets/issues/2178

Added capability to support more than 1 API, but only OpenWeatherMap is implemented at the moment.

Fully functional,
I believe icons needs some tweaking and the translation testing/reworking because a huge amount of code was changed.

### CODE REVIEW

**Comment by Ahmad-Magdy-Osman** [comment]
Any idea how long until this is available for end users?

**Comment by Gr3q** [comment]
@mockturtl tell me what I need to change and I change it.

Apologies for not using the Code Guide, I was in a hurry and did not read it properly, I plan to fix that in another pull request with another API implementation.

**Comment by dopeboy** [comment]
(Not affiliated with the repo - just commenting as a fan)

Thanks for your hardwork, @Gr3q. I did a quick test and found the following:

* The refresh button doesn't work
* Changing the city doesn't always work
* More on the UX side - we may need a little more guidance on entering a location because if you enter a US city like mine, it may or may not work. But <zipcode>,<country> works - I only learned that from the OW docs. 

Once I got past that, I had a working applet :)

For those needing this immediately, remove the existing weather applet and

```
git clone https://github.com/Gr3q/cinnamon-spices-applets.git
cp -r cinnamon-spices-applets/weather@mockturtl/ ~/.local/share/cinnamon/applets
```
The applet should show in the Cinnamon applets list. 

Head over to [OpenWeather](https://openweathermap.org) and create an account. Get the API key. Open the applet configuration and plop it in. If you don't live in a major city, it might not pick up your location. I'd suggest reading [here](https://openweathermap.org/current#one) to ascertain your location. 

If you run into wonky errors with the applet, try refreshing cinnamon (alt+f2, type in 'r')

**Comment by Gr3q** [comment]
@dopeboy Thanks for the feedback
I will iron out the refresh/reload stuff and hopefully make the Settings page more user friendly, most likely later this week.

I'm surprised that it works with zip code as I never actually implemented that (just checked and [zip,country] code can be used with the same query string as [city,country],thats why)

I will keep this pull request open until I fixed the things mentioned.

**Comment by nalim** [comment]
> (Not affiliated with the repo - just commenting as a fan)
> 
> Thanks for your hardwork, @Gr3q. I did a quick test and found the following:
> 
> * The refresh button doesn't work
> * Changing the city doesn't always work
> * More on the UX side - we may need a little more guidance on entering a location because if you enter a US city like mine, it may or may not work. But `<zipcode>,<country>` works - I only learned that from the OW docs.
> 
> Once I got past that, I had a working applet :)
> 
> For those needing this immediately, remove the existing weather applet and
> 
> ```
> git clone https://github.com/Gr3q/cinnamon-spices-applets.git
> cp -r cinnamon-spices-applets/weather@mockturtl/ ~/.local/share/cinnamon/applets
> ```
> The applet should show in the Cinnamon applets list.
> 
> Head over to [OpenWeather](https://openweathermap.org) and create an account. Get the API key. Open the applet configuration and plop it in. If you don't live in a major city, it might not pick up your location. I'd suggest reading [here](https://openweathermap.org/current#one) to ascertain your location.
> 
> If you run into wonky errors with the applet, try refreshing cinnamon (alt+f2, type in 'r')

small correction:

cp -r ~/cinnamon-spices-applets/weather@mockturtl/files/weather@mockturtl ~/.local/share/cinnamon/applets/

**Comment by mockturtl** [comment]
@Gr3q Wow!  It's working for me.

> tell me what I need to change and I change it.
> Apologies for not using the Code Guide, I was in a hurry and did not read it properly, I plan to fix that in another pull request with another API implementation.

No worries, I just wanted to keep the style consistent, and certain choices looked popular at the time.  The problem now might be choosing among popular auto-formatting tools. :laughing: 

The README should explain how to get an API key, and any known issues (maybe another call for translators?).  Otherwise, :+1: :+1: from me.

Amazing work!

**Comment by cranes-bill** [comment]
@Gr3q Firs of all, thank you very much from me as well!
Just as information: I noticed two things you might take a look _(if you have ability of course)_.
First one, if I add the applet to the panel, do not enter a location and then remove it, this triggers an infinite high CPU load after some time.
And second one, I'm receiving the following message when I'm appending the applet to the panel:
`Invalid setting type 'button' for setting key 'getLocation' of applet/desklet uuid weather@mockturtl`
However, the applet seems working at all, so good job.

Once again thank you and sorry for my bad English!

**Comment by dopeboy** [comment]
@Gr3q - I'll fill out the README - will doing it later today or early tomorrow PST.

**Comment by pavolgaj** [comment]
Hi,
I want to try it. But, it doesn't work. I set location and API. I tested it using web browser: `api.openweathermap.org/data/2.5/weather?q={city name},{country code}&appid={api}` and it works. 
But, refresh in applet not works at all. I found this error in .xsession-errors:
`(cinnamon:1603): Cjs-WARNING **: 09:53:56.096: JS ERROR: TypeError: json is null
anonymous/refreshWeather/<@/home/pavolg/.local/share/cinnamon/applets/weather@mockturtl/applet.js:430:11
soupQueue@/home/pavolg/.local/share/cinnamon/applets/weather@mockturtl/applet.js:412:7`

**Comment by dopeboy** [comment]
@pavolgaj - I had to restart Cinnamon to get past that error. It seems removing and reinstalling the applet didn't always load the new one.

@Gr3q - I've pushed [some changes](https://github.com/Gr3q/cinnamon-spices-applets/pull/1) to your fork.

**Comment by Gr3q** [comment]
@pavolgaj please try it with the latest changes in my fork, also can you send me what you put into the location field?

Otherwise, **this pull request is ready to go**.

@mockturtl Do you know who needs to review and approve/reject the Pull request?

**Comment by jaszhix** [comment]
Hi, nice work. I tested this and it seems to work pretty well. One small issue I found on startup:

`Cjs-Message: 10:48:31.343: JS LOG: [LookingGlass/error] Invalid setting type 'button' for setting key 'getLocation' of xlet weather@mockturtl`

**Comment by archmunky** [comment]
When I use this it keeps flashing with the weather info and "service not available" every few seconds.  any idea what could be causing this problem?

**Comment by Gr3q** [comment]
@archmunky Are you using the applet with the latest changes included?

**Comment by mockturtl** [comment]
> Do you know who needs to review and approve/reject the Pull request?

Ping @jaszhix whenever you're ready.

**Comment by cranes-bill** [comment]
I think everything works fine now. Just one more small thing - when degrees are Celsius, it shows 1° more then json data, so i think, also according to [this](https://img.purch.com/w/640/aHR0cDovL3d3dy5saXZlc2NpZW5jZS5jb20vaW1hZ2VzL2kvMDAwLzA1Ny8zNjcvaTAyL3RlbXAtc2NhbGVzLmpwZz8xMzgwMjU4MTk0) table, there is a typo [here](https://github.com/Gr3q/cinnamon-spices-applets/blob/master/weather%40mockturtl/files/weather%40mockturtl/applet.js#L928) and it should be:
```diff
-      return Math.round((kelvin  - 272.15) * 10)/ 10;
+      return Math.round((kelvin  - 273.15) * 10)/ 10;
```
Thanks a lot again for your work!

**Comment by mxyzplx** [comment]
First, thanks for your work on this. I've been using the one from git, and it's working very well for me. 

Second, and this is by no means a big deal, but is there a way to get the temperature rounded to two digits? I believe the original did that (may be wrong and can't check now because it's not functioning), and it saves a little space on the panel.

**Comment by Odyseus** [comment]
Hello, everybody.

@Gr3q: The problem with the error reported by @jaszhix is that you are binding the applet settings in a loop and the button is listed in the **KEYS** constant. Since the **button** type field isn't a setting, it doesn't need to be bound. You could just remove **WEATHER_GET_LOCATION** from the **KEYS** array and the error will go away.

**Comment by Gr3q** [comment]
@Odyseus thank you for explaining that. Do you know is there documentation what I can educate myself with so these kind of noob mistakes don't happen again?

**Comment by mxyzplx** [comment]
> @mxyzplx The temperature came from Yahoo API as Celsius or Fahrenheit so I don't know either. If the preference is to have whole numbers, I can do that. Although I would change this to an user setting later on.

Yep, that's exactly what I was thinking of, a setting for whole numbers.

**Comment by Odyseus** [comment]
@Gr3q: The **button** widget is described in the documentation as a *non-setting* widget. As such, it should never be bound to a setting. It would be like trying to bind a **label** widget.

On the other hand, I must admit that the documentation is kind of confusing. Because, for example, **button** and **label** are listed under **Other settings types** and then are described as *non-setting*. In fact, calling them *settings types* is misleading. What they really are is **widget types**; some can control settings and some don't (*non-setting* widgets).

**Comment by collinss** [comment]
@Gr3q For the documentation, you'll need to install devhelp, and the cinnamon-doc package (for debian based distros like Mint and Ubuntu) if they're not already installed (note: building cinnamon yourself will usually also build cinnamon-doc). The documentation for the settings api is found under Cinnamon Tutorials in devhelp.

**Comment by Gr3q** [comment]
@collinss @Odyseus Thank you, now I know where to look for these things.

* Added Fix for button, had a look on the state of the translations as well, the old stuff still works. 
* More resistance against API response errors and against missing fields in the json.
* Temperature is rounded to whole numbers, adding this as an option in another version.

@jaszhix Unless you guys find some critical bug, this pull request is ready to go.

**Comment by cranes-bill** [comment]
@Gr3q 
Just to have in mind for the next changes, currently the applet are showing **sunrise / sunset** time twice. For example: **7:48 7:48** 
Thanks! :+1:

**Comment by Gr3q** [comment]
@cranes-bill yeah thank you, I noticed it after merge, also there is no timezone calculation for them either so its always showing utc... fixed both on my fork but the tz stuff is pretty ugly

**Comment by Gr3q** [comment]
@pavolgaj  I don't know for sure, but you get obviously wrong times if you set your location to for example china (showing sunrise at 22:00, system tz is GMT) so its either displaying in UTC or in the systems timezone (possibly the latter). 

The thing is it the applet should't use system locale/tz information for a time what can be in a different tz.

I'm gonna test this tonight, swapping my system TZs while making sure the sunrise/sunset times for a location with wierd tz offset (probably El Aaiun) always displays the correct time for that location.

**Comment by pavolgaj** [comment]
@Gr3q I tried it. It displays times for selecting location in the system TZ. 
Few examples: 
- location: central europe, TZ: central europa - sunrise at 7:00-8:00
- location: central europe, TZ: Japan - sunrise at 15:00-16:00
- location: Japan, TZ: Japan - sunrise at 7:00
- location: Japan, TZ: central europe - sunrise at 23:00

So, times are always displayed in system TZ.

**Comment by Gr3q** [comment]
@ So it is, thank you.

**Comment by dene14** [comment]
@Gr3q Thank you so much!!!

**Pull request merged**
