### PR TITLE
weather@mockturtl Update 3.0.4

### LINKED ISSUE #3603: weather@mockturtl Toggle Hourly Forecasts over days
@Gr3q

Here is an idea and feature request to make the expanded weather applet's access to hourly forecasts hopefully a little bit more intuitive and easier to use?

If there is a Hourly Forecast make the "Today" text a clickable button (that works exactly like the bottom arrow up), and could look like this:

weather-exp-today

If the Hourly Forecast goes over to the next day in time, make "Tomorrow" text a button, and when clicked expands and shows the tomorrow hours something like this (maybe from 01 hrs and like anchor links on web pages?):

weather-exp-tomorrow

If the Hourly Forecast goes beyond tomorrow the next weekday gets a button and so on.

Is this interesting to have, and doable in a good way or at all?

### LINKED ISSUE #3637: Longitude and latitude fields are integer only
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors

 ```

**Notify author of applet**
@

**Issue**
The longitude and latitude fields in the save locations form are integer only
Fixed point numbers are truncated to integers

**Steps to reproduce**
Click on add a new entry
Fill in the fields
On saving long and lat are trucated to integer

**Expected behaviour**

**Other information**

### PR DESCRIPTION
**Pull request by Gr3q**
Changes:
* Add declarations for some of the cinnamon js files and organizing declarations better (and add more when I feel up to it again). Technically anyone can use it if want to use Typescript by including the declarations folder into their tsconfig.json file, but whatever.
* Resolves #3603 
* Add minutely precipitation under current condition, when there is any (and the setting is on)
* Add more tooltips to settings
* OpenWeatherMap can also display Precipitation chance if there is no volume specified
* Autoformat 3.8 and new declaration files
* Fixes #3637

Sorry about the lots of commits, I was developing on 2 branches in parallel, but the diff checks out 

@KAMI911 @Pjotr123 @jorgenqv @sveinki @serkan-maker @FabienRCT @Alan01 @French77 there are some changes in the translations (a few additions) this time as well. I'm going open this PR for review on Sunday.

### CODE REVIEW

**Comment by brownsr** [comment]
Lots of commits is fine.  Mixing indentation changes with code changes is more difficult as it obscures what is going on.  But it's fine, seen far more difficult changes to review ;-) Look forward to seeing this finalised, as ever...

Regards

Simon

**Comment by NikoKrause** [comment]
@brownsr You can hide indentation changes, when you review code on GitHub. There's an option called `Hide whitespace changes` under the cog symbol:

grafik

**Comment by brownsr** [comment]
Neat, thanks. :-)

**Comment by NikoKrause** [comment]
@Gr3q I've updated the German translation based on the latest commit of this pull request. Can you include it in your PR? Thx.

[de.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/6054949/de.po.zip)

**Comment by serkan-maker** [comment]
@Gr3q  I updated the Turkish translation, can you add it?  3.0.4 version. thank you
[tr.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/6056615/tr.po.zip)

**Comment by Gr3q** [comment]
@serkan-maker I added it thank you. This makes PR #3649 Pr obsolete

**Pull request merged**
