### PR TITLE
Finnish translations for applets

### PR DESCRIPTION
**Pull request by mahtiankka**
New fi.po files for programs redshift, promodo, vboxlauncher, clipboard-qr and sessionmanager.

I made a pot file for the better-backgrounds program according to the instructions. I created a PO folder and a fi.po file.

### CODE REVIEW

**Comment by mahtiankka** [comment]
I have done many translations now. I hope they will be approved soon. Thank you.

Paneeli

**Comment by brownsr** [comment]
Unfortunately there is one change there to the johnbrettdev applet that isn't a translation.  Could you take a look at this please, and ideally remove it ?

Regards

Simon

**Comment by mahtiankka** [comment]
> Unfortunately there is one change there to the johnbrettdev applet that isn't a translation. Could you take a look at this please, and ideally remove it ?
> 
> Regards
> 
> Simon

I did what you asked. I deleted the .py file. The problem remains that the program's rss http links are not working, but that is now feeds@janbrettdev's problem.

Kimmo (mahtiankka)

**Comment by mahtiankka** [comment]
I have had a goal to translate all the cinnamon-spices-applets into Finnish. There are now 24 programs awaiting publication. 3000 lines of text, two weeks of work. The text is not only translated, but each program is also tested. 
I have used the cinnamon-spices-makepot command according to the README instructions. If there have been new changes to the POT file, I have also added them.

I can't continue my own work if nothing is certain about the publication.

**Pull request closed without merging**
