### PR TITLE
Spices update - Update icon.png - Fixes #2200

### LINKED ISSUE #2200: SpicesUpdate@claudiux - customized color is chosen twice
@claudiux
Tiny bug found:
In settings click button to choose an icon color.
Click on the "+"-sign to select a new custom color.
Click "Choose" button -> the chosen color is displayed twice

Another hint:
Concerning the default icon color in case of updates - I made the suggestion to change it from blue to the Cinnemon orange, but unfortunately you chose a quite dark brown tone, also for the applet logo.
If it was intended, it's ok (you're the author and everyone can choose his own color of course), but I meant the orange logo like in the top of https://cinnamon-spices.linuxmint.com/applets/view/309 or similar.
That's #dc682e or #dc6830 or shiny #f57900 or your previous icon.png color #eb9122, and that might be more notable.

Greetings

### PR DESCRIPTION
**Pull request by claudiux**
Hi @jaszhix,

Can you merge this branch with your master one, please?

Best regards.
Claudiux

### CODE REVIEW

**Comment by claudiux** [comment]
Thank you @jaszhix !

**Comment by claudiux** [comment]
Hi @jaszhix,

I do not understand why the icon in https://cinnamon-spices.linuxmint.com/applets/view/309 is not the same.

**Comment by jaszhix** [comment]
It looks the same to me. Does it look different in an incognito window? Probably browser caching.

**Comment by claudiux** [comment]
I tried with another browser; same thing. The color of the icon in the page is #c58e22. The color of this icon is #eb9122.

**Comment by jaszhix** [comment]
I used chrome's eye-dropper tool in devtools and it shows #eb9122 for me.

image

**Comment by claudiux** [comment]
OK, maybe a remote cache issue for me. Thanks for your tests, @jaszhix !

**Comment by claudiux** [comment]
All is OK now.

**Pull request merged**
