### PR TITLE
mylauncher@markbokil.com: Add Dutch translation

### PR DESCRIPTION
**Pull request by qadzek**

### CODE REVIEW

**Review by rcalixte — APPROVED** [review]

**Comment by JTi65** [comment]
Hello, how to add fi.po in yours program?

**Comment by rcalixte** [comment]
> Hello, how to add fi.po in yours program?

Hello, there are instructions [here](https://community.linuxmint.com/tutorial/view/2521) and a [Forum thread](https://forums.linuxmint.com/viewtopic.php?t=413986) with more context.

Shout if you have any questions but feel free to open a new Issue instead of this closed Pull Request.

**Comment by JTi65** [comment]
Hello, how to add fi.po in yours program?

> > Hello, how to add fi.po in yours program?
> 
> Hello, there are instructions [here](https://community.linuxmint.com/tutorial/view/2521) and a [Forum thread](https://forums.linuxmint.com/viewtopic.php?t=413986) with more context.
> 
> Shout if you have any questions but feel free to open a new Issue instead of this closed Pull Request.

Hello, thanks for your help. Its work very well.

**Comment by rcalixte** [comment]
> Hello, thanks for your help. Its work very well.

If you have a translation and want to make it available for others, feel free to attach it or open a Pull Request to have it included by default.

**Pull request merged**
