### PR TITLE
[Sensors@claudiux] Update .pot and fr.po files and code cleanup

### PR DESCRIPTION
**Pull request by claudiux**
@brownsr 
Hi Simon,

Just a code cleanup and an update of the .pot and fr.po files.

Can you merge this branch with your master one, please?

Kind regards.
Claudiux

### CODE REVIEW

**Comment by claudiux** [comment]
Thank you @brownsr but... Why this applet is not referenced on https://cinnamon-spices.linuxmint.com/applets/latest ?

**Comment by brownsr** [comment]
There has been some work on the server, not by me, but perhaps there is
still work going on that affects the refresh.  Simon

**Comment by brownsr** [comment]
Ah, might have found something.  There's a validate-spice script in the repository that is highlighting that the icon is not square.  Perhaps the server load script makes a similar check and is refusing to load it for that reason.

Regards

Simon

**Comment by claudiux** [comment]
I don't understand:

`$ identify -format '%w' icon.png` and `$ identify -format '%h' icon.png`: both return 48.

`$ identify -format '%w' files/Sensors@claudiux/icon.png` and `$ identify -format '%h' files/Sensors@claudiux/icon.png`: both return 48.

`$ identify -format '%w' files/Sensors@claudiux/icons/icon.png` and `$ identify -format '%h' files/Sensors@claudiux/icons/icon.png`: both return 48.

The `validate-spice` script returns, on my computer: ✔ ✔ ✔ ✔ ✔ Sensors@claudiux is valid!

Well, I will make a new PR.

Regards.
Claudiux

**Pull request merged**
