### PR TITLE
[Cinnamenu@json] fix app icon label alignment

### PR DESCRIPTION
**Pull request by basilky**
@fredcw 
Before 
Screenshot from 2020-04-21 16-27-13
 After
 Screenshot from 2020-04-21 16-36-04

### CODE REVIEW

**Comment by brownsr** [comment]
ping @fredcw

**Comment by fredcw** [comment]
@basilky Sorry about the delay in replying. Your pictures have gone and I don't see the problem that this fixes. Are you using the 3.x version of cinnamon?

**Comment by basilky** [comment]
@fredcw Pictures are loading fine for me. App icon labels are aligned slightly to the right for me, with respect to app icons. I'm using Cinnamon 4.4.8 on LM 19.3.

**Comment by basilky** [comment]
@fredcw app label icon is having css class ['menu-application-button-label'](https://github.com/linuxmint/cinnamon/blob/6ead01c28d584fe864602d74cd9b3ed7cdd29362/data/theme/cinnamon.css#L1037). I think the padding-left:5px is causing this issue. This padding is useful in list view to separate icon from label. But in grid view, this causes the label to be misaligned.

**Comment by fredcw** [comment]
@basilky You're right. I don't know why I didn't spot that before. I've added the line "style: 'padding-right: 5px; padding-left: 5px' to take account of rtl scripts as well. The text is centered now but the icons are still slightly to the left, not sure why. Thanks.

**Comment by brownsr** [comment]
so @fredcw am I waiting for a new version of the applet from you, or do you want me to pull this ?

S

**Comment by fredcw** [comment]
@brownsr Ok, thanks. I wasn't sure of the process. I've created a new PR.

**Comment by brownsr** [comment]
presumed included in @fredcw PR.

**Comment by basilky** [comment]
@brownsr @fredcw  The issue is still there in the latest version.

**Comment by fredcw** [comment]
@basilky I added "padding-right: 5px" like you said:

` 
this.label = new Label({
    text: this.buttonState.app.name,
    style_class: 'menu-application-button-label',
    style: 'padding-right: 5px; padding-left: 5px'
});
`
Why did it not fix it?

**Comment by basilky** [comment]
I think padding-left is not required in the style. I added padding-right only to negate the left padding added by 'menu-application-button-label'

**Pull request closed without merging**
