### PR TITLE
[temperature@fevimu] Change owner from jaszhix to claudiux

### PR DESCRIPTION
**Pull request by claudiux**
Hi @brownsr,

Not wanting to see disappear a very useful applet to which I contributed, I propose to become the owner of `temperature@fevimu` in order to be able to maintain it.

Please note I have used the `codeowners_creator.py` script to change the `CODEOWNERS` file.

Best regards.
Claudiux

### CODE REVIEW

**Comment by jaszhix2** [comment]
There's no risk of it disappearing. I pulled Cinnamenu because Clem pulled my other applets, and have been taken advantage of. You guys are free to fork anything that's disappeared as a result of me as long as it doesn't reference me.

**Comment by claudiux** [comment]
@jaszhix2 Do you want I close this PR? If yes, I will do it quickly.

**Comment by brownsr** [comment]
Happy to see you want to maintain this applet @claudiux.  There are quite a few applets that have passed between different maintainers when the original author is no longer maintaining it.

Regards

Simon

**Comment by jaszhix2** [comment]
@claudiux Not at all, I was just explaining why anything would disappear since you referenced me in the PR title.

**Pull request merged**
