### PR TITLE
collapsible-systray@feuerfuchs.eu: Fix St-CRITICAL warnings; more user-friendly behavior if there are no icons to hide/reveal

### PR DESCRIPTION
**Pull request by Feuerfuchs**
Fixing the errors and usability problems described here: https://github.com/linuxmint/cinnamon-spices-applets/pull/710#issuecomment-302641766

### CODE REVIEW

**Comment by Feuerfuchs** [comment]
Turns out the reason for the errors was that I had used `actor.reparent()` to move icons from the always-visible container to the maybe-visible container and vice versa.

**Comment by NikoKrause** [comment]
please do not add `dangerous` and `last-edited` flag in the metadata.

**Comment by NikoKrause** [comment]
You use `const _ = imports.applet._;`
Do "Collapse", "Expand" and ""No icons to hide/reveal" translate for you?

I think they don't.

**Comment by Feuerfuchs** [comment]
> please do not add dangerous and last-edited flag in the metadata.
I was sure I had removed them, but they are gone now. I guess I still had them in my own repo.

> Do "Collapse", "Expand" and ""No icons to hide/reveal" translate for you?
Yes. I use the same method for the GPaste applet and it works fine there, too.
bildschirmfoto vom 2017-05-19 12-59-24

**Comment by NikoKrause** [comment]
Ok.
The dangerous flag will appear again. I always make sure to checkout the metadata.json before creating a PR, if I haven't changed it on purpose.

**Comment by NikoKrause** [comment]
Can I squashe merge (then there will be shown only 1 commit in the history) or do you want the commits to be separated as they are?

**Comment by Feuerfuchs** [comment]
> The dangerous flag will appear again. I always make sure to checkout the metadata.json before creating a PR, if I haven't changed it on purpose.

Ah okay, that's good to know!

> Can I squashe merge (then there will be shown only 1 commit in the history) or do you want the commits to be separated as they are?

Feel free to squash them.

**Pull request merged**
