### PR TITLE
Add applet Rate currency

### PR DESCRIPTION
**Pull request by AleksiMagner**

### CODE REVIEW

**Comment by AleksiMagner** [comment]
Everything seems to be done by the rules. No response for a long time. Is something wrong again?

**Comment by Gr3q** [comment]
Looks good to me. 

Please understand that everyone doing this in their free time so sometimes they don't have time to respond or review for a while.

**Comment by AleksiMagner** [comment]
OK, I understand. All the updates in the code I publish through the new PR only after closing this, right?

**Comment by Gr3q** [comment]
If this PR is open and you want to change, fix things, all you need to do is to commit and push those changes to your branch (what you used to open this PR).

When the PR is accepted and is merged, and you want to add a new feature, you _(this is my actual workflow)_:
1. Rebase your Fork's master branch to cinnamon's original master branch _(to be in line with the original repo's state)_, which you can do:
   1. Add cinnamon's original repo as a remote (do this only once): ```git remote add <give-it-a-name> https://github.com/linuxmint/cinnamon-spices-applets.git```. I use "mint" as the remote name.
   2. Fetch from all your remotes ```git fetch --all```
   3. Switch to your master branch ```git checkout master```
   4. Rebase your master to cinnamon's master ```git rebase mint/master```
   5. Push it to your remote ```git push```
Now you are in line with cinnamon's repo state.

2. Create a new branch for your feature from master, switch to branch, etc. Exactly what you did with this PR.

**Comment by brownsr** [comment]
Attila is right, I haven't had time to look at this yet. There's more to
review for a new applet that an update of an existing one. Will get to it
soon.

**Pull request merged**
