### PR TITLE
weather@mockturtl update 3.0.3 - fixes

### PR DESCRIPTION
**Pull request by Gr3q**
**This update changes the .pot file**, so I will give a week for anyone to update translations either separately or PR into my branch, or raise any concerns about it (by commenting below or commenting on the code). Especially because there were a lot of discussion about translations in the related issues.

@KAMI911 @Pjotr123 @jorgenqv  @sveinki @serkan-maker @FabienRCT @Alan01 @French77 If you don't want me to ping you again about this, comment below, otherwise ignore or do what you like. If you have any questions or concerns, let me know.

Changes: 
* Fixes [#3508](https://github.com/linuxmint/cinnamon-spices-applets/issues/3508), just a minor issue with naming
* Fixes [#3539](https://github.com/linuxmint/cinnamon-spices-applets/issues/3539) - Revert capitalization of every word in the applet label.
* Fix some text in the settings-schema, they didn't make much sense or were missing some explanations
* Change Temperature units to be capitalized
* Fixes [#3556](https://github.com/linuxmint/cinnamon-spices-applets/issues/3556)
* Fixes [#3554](https://github.com/linuxmint/cinnamon-spices-applets/issues/3554)
* Fixes [#3567](https://github.com/linuxmint/cinnamon-spices-applets/issues/3567)
* Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/3560
* Changed author while still crediting the original author per @NikoKrause s request, hope it's ok @mockturtl

### CODE REVIEW

**Comment by jorgenqv** [comment]
Ok, I will try to do pull request to your `weather-dev` branch. Fingers crossed that I don't break anything ;-)

**Comment by Gr3q** [comment]
> Ok, I will try to do pull request to your `weather-dev` branch. Fingers crossed that I don't break anything ;-)

If you add my fork as a remote, branch off weather-dev and create a PR back to it from your fork there shouldn't be any problems

**Comment by jorgenqv** [comment]
Ah sorry, maybe I messed up, did two PR to your weather-dev and now I got 3 active branches: patch-1, patch-2 and weather-dev. Usually I just do PR to master via the web interface (by pasting my new update in edit mode and create the PR from there). When merged I just delete the created branch and merge upstream/master and push origin master. Hope this is ok?

**Comment by Gr3q** [comment]
@jorgenqv There are no problems with you PRs on my branch

**Comment by jorgenqv** [comment]
> There are no problems with you PRs on my branch

Ok nice, thanks! :)

**Comment by Gr3q** [comment]
@brownsr This PR is ready for review

**Pull request merged**
