### PR TITLE
weather@mockturtl Update 2.4.8

### PR DESCRIPTION
**Pull request by Gr3q**
Changes:

* Update Openweathermap to their unified API call
* Add information on DarkSky aquisition to Readme
* Fix translation issues in files other than applet.js
* Add Yahoo Weather to the available services
* Fix issue when system time is changed backwards, the applet stops updating until time gets to the time previously set
* Change 'Updated' to 'As of' to have a clearer meaning.

Tested on Cinnamon version 3.0 as well.

### CODE REVIEW

**Comment by muzena** [comment]
@Gr3q 
After update Openweathermap do not work anymore.

**Comment by Gr3q** [comment]
@muzena Do you have any (Debug) logs you can share with me?

**Comment by muzena** [comment]
@Gr3q 
Where can I found debug logs?

**Comment by muzena** [comment]
I fix this by removing:
/.cinnamon/configs/weather@mockturtl/54.json

**Comment by Gr3q** [comment]
@muzena Glad to hear that, it seems the settings become incompatible between the 2 versions (not that I changed them in a big way)

**Pull request merged**
