### PR TITLE
[temperature@fevimu] Option added: Change color when the temperature becomes High or Critical

### PR DESCRIPTION
**Pull request by claudiux**
Also fixes a display issue.

@brownsr Can you merge this branch with your master one, please?

Best regards.
Claudiux

### CODE REVIEW

**Comment by claudiux** [comment]
Now, it works well. I have nothing more to add.

**Comment by claudiux** [comment]
Well, almost! ;)

**Comment by brownsr** [comment]
treated as including a bugfix.

**Comment by claudiux** [comment]
@brownsr Thank you Stephen !

**Pull request merged**
