### PR TITLE
[moonphase@techi-freki] Adds percentage display to label and tooltip.

### PR DESCRIPTION
**Pull request by sphh**
Display of phase name and/or phase percentage can be independently configured for the label and the tooltip.

### CODE REVIEW

**Comment by sphh** [comment]
@Techi-Freki

**Comment by sphh** [comment]
We could also add the number of days to the next full/new moon. Would that be appreciated? (But thinking this even further, this would call for a format string, complicating it for the average user … What do you think?)

**Comment by claudiux** [comment]
It works fine. I was thinking of having the date of (or number of days before) the next Moon phase, displayed in the tooltip.

**Comment by claudiux** [comment]
@sphh Please change the version number in `metadata.json`.

**Comment by sphh** [comment]
I can change the version number, no problem, but I wanted to leave this to @Techi-Freki. Firstly, maybe s/he wants to make some changes, add a new feature or has a certain idea about the version number. I would have changed it to 0.1.0.

I also think, adding more display options calls for a format string. Let's wait a couple of days and see, what @Techi-Freki thinks about it.

**Comment by claudiux** [comment]
Ping @Techi-Freki

**Comment by Techi-Freki** [comment]
Hey guys, this all looks good to me. I'm surprised this thing is getting as much engagement as it is. Thanks! I appreciate it.

**Review by rcalixte — APPROVED** [review]

**Comment by sphh** [comment]
@Techi-Freki: Glad that you like it.

What is your opinion about adding other information as mentioned in https://github.com/linuxmint/cinnamon-spices-applets/pull/5058#issuecomment-1777653682 ff.?

**Comment by Techi-Freki** [comment]
I'm ok with it. The only other thing I was looking to implement was an indicator that displays a lunar eclipse and maybe moon set and rise times. But I might need to gather more info from the user (geolocation) which I'm not really wanting to do at this point because I have a strong privacy streak in me, that might change soon.

I'm really not sure how to properly display those other than showing them in the settings section because I think showing it in the cinnamon task bar may be a bit much. I'm open to suggesting on the front end display of it (I'm a back end dev by trade, so front end and design isn't my strong suite).

I already have those icons added as part of the icon set class. As far as the versioning is concerned, this is my first open source project that I've released and the v0.0.1 was a bit of a mistake on my part. It should have been 1.0.0 but we can change it as we deem necessary. Thanks again for both of your additions. This has been pretty exciting. I'm looking to get some Spanish and maybe Italian and Japanese translations added.

**Comment by claudiux** [comment]
Hi @Techi-Freki 

Displaying lunar eclipse and moon set and rise times: very good idea!
For geolocation, simply add a switch in the settings, in a "Privacy" section. Depending on the value of this switch, the user may be offered the display of the lunar eclipse and the moonrise and sunset times. A replica of this switch can be displayed in the applet's contextual menu, or in a (non-contextual) menu that would then have to be created.


To know the status of translations for your applet:
https://github.com/linuxmint/cinnamon-spices-applets/blob/translation-status-tables/.translation-tables/tables/moonphase%40techi-freki.md 

Ping @Dragone2 @haggen88 for Italian and Spanish translations.

**Pull request merged**
