### PR TITLE
SpicesUpdate@claudiux - Update de.po

### PR DESCRIPTION
**Pull request by Mintulix**
Hi claudiux,
even if I have to make a new Pot file - I think the forced reinstall of a spice is handled a bit illogical.

Why do I have to check the first box if I just want to repair/reinstall a spice? Perhaps I don't want it to be checked regularly? So I think checking the second box should be enough. What do you think?

Kind regards

### CODE REVIEW

**Comment by claudiux** [comment]
Hi @Mintulix,

You are right. I will change that.

Kind regards

**Comment by Mintulix** [comment]
Hi @claudiux, kind reminder: you said you would change the behavier of the second checkbox. Did you? At least you didn't change the hint
If you want to get the latest version of an xyz now, check both boxes.
After that you get a new German translation ;-).

**Comment by claudiux** [comment]
Hi @Mintulix,

I tried to do that. It was source of many bugs. To implement this feature, I need to rewrite much of the code. I do not have time now. I'll think about it.

Thank you for your patience and your understanding.

**Comment by Mintulix** [comment]
@claudiux, ok, then it might not be worth it. Thanks for the information. And don't worry about patience - I have to thank YOU! Hey, it will be in Cinnamon 4.4, congratulations! Translation is following...

**Comment by claudiux** [comment]
@Mintulix Thank you very much!

**Pull request merged**
