### PR TITLE
PDFManager@cinnamon.org: language bugfix

### PR DESCRIPTION
**Pull request by mickaelalbertus**

### CODE REVIEW

**Comment by collinss** [comment]
Why did you remove all the semicolons? It is proper syntax to include them.

**Comment by mickaelalbertus** [comment]
Because it doesn't change anything (I've looked other spice to check). It was the plugin I've created but languages were not supported anymore so I suggest this modifications. I will correct other bugs in few days and add more functionality.

**Comment by mickaelalbertus** [comment]
I will rewrite all semicolons in a future update. I've checked and you're right it's proper

**Comment by NikoKrause** [comment]
> languages were not supported anymore so I suggest this modifications

The problem why the languages are not supported anymore is, because of a wrong UUID in `Gettext.dgettext`, i.e. you can change this
```
function _(str) {
   let customTranslation = Gettext.dgettext("PDFManager", str);
   if(customTranslation != str) {
      return customTranslation;
   }
   return Gettext.gettext(str);
}
```
to this
```
function _(str) {
   let customTranslation = Gettext.dgettext("PDFManager@cinnamon.org", str);
   if(customTranslation != str) {
      return customTranslation;
   }
   return Gettext.gettext(str);
}
```

**Comment by mickaelalbertus** [comment]
Yes, I understood so I changed that :)
I'm a beginner of Github and I'm not an expert of programming so sorry for my mistakes (semicolons and the previous pull request)

**Comment by NikoKrause** [comment]
No need to apologize.
The semicolons are not a mistake. It makes no difference, if they are there or not.

**Comment by NikoKrause** [comment]
Can you change the author in the info.json file of your applet from `mickaelalb` to your GitHub user name `mickaelalbertus`?

**Comment by mickaelalbertus** [comment]
Sure, I didn't have Github account when I've created this one. I do on the next pull request or I modify this one?

**Comment by NikoKrause** [comment]
> I do on the next pull request or I modify this one?

It's up to you. You can create another commit in you branch `PDFManager@cinnamon.org.bugfix` if you want to. It will be added to the pull request here.

Should this be merged then?

**Comment by mickaelalbertus** [comment]
Yes I want it to be merged because I don't know when I will correct all other bugs. I will also lighten python scripts.

**Pull request merged**
