### PR TITLE
[radio@driglu4it] Remove Playerctl

### PR DESCRIPTION
**Pull request by jonath92**
Currently we use playerctl for stopping the radio and increasing/decreasing the volume. This has several disadvantages - users have to install the package and it is very difficult to trigger actions when the volume is changed or the radio player paused from outside of the applet (e.g the sound applet). This pull request removes the playerctl dependency by using the D-Bus interface instead (similar to the sound applet). 

@NikoKrause

### CODE REVIEW

**Comment by NikoKrause** [comment]
@Driglu4it Do you mind if I add @jonath92 as current maintainer of your radio applet? You don't have to, if you don't want to, though.

**Comment by Driglu4it** [comment]
> @Driglu4it Do you mind if I add @jonath92 as current maintainer of your radio applet? You don't have to, if you don't want to, though.

I completely agree, because moved on to developing plasmoids for Plasma 5. What do I need to do to transfer rights?

**Comment by NikoKrause** [comment]
I'll take care of it. Thx.

**Comment by Driglu4it** [comment]
> I'll take care of it. Thx.

It's my pleasure. I am glad that development will continue. Thank you!

**Comment by jonath92** [comment]
I am very thankful for this honour and for your contributions @Driglu4it  and @NikoKrause!

**Pull request merged**
