### PR TITLE
Remove directory-menu@torchipeppo since it is not working

### PR DESCRIPTION
**Pull request by rcalixte**

### CODE REVIEW

**Comment by anaximeno** [comment]
Wouldn't it be better to just point them to older versions of cinnamon lower than 5.4 instead? Unless this is the only way they would not show up in current versions, it seems a bit extreme.

**Comment by rcalixte** [comment]
> Wouldn't it be better to just point them to older versions of cinnamon lower than 5.4 instead? Unless this is the only way they would not show up in current versions, it seems a bit extreme.

[This](https://github.com/linuxmint/cinnamon-spices-applets/pull/5377#issuecomment-1897670714) was the reason it was removed. Apparently it wasn't working on earlier versions either. If this isn't the case, we can definitely revert and just disable it until it's fixed for 5.4. Can you confirm it's fine for 5.2 and lower?

**Comment by claudiux** [comment]
I can confirm that this applet works on 5.0 and 5.2.

**Comment by rcalixte** [comment]
Were either of you able to confirm the right-click issue identified by @fredcw?

**Comment by torchipeppo** [comment]
Just reproduced @fredcw 's issue reproduced on Cinnamon 5.0.7

**Comment by anaximeno** [comment]
Oh, ok @rcalixte, I thought it was an older applet since @claudiux said it was working on older versions, if it is a new one then there's no problem. 

@torchipeppo I believe you can submit a new PR again if you manage to solve the [issue](https://github.com/linuxmint/cinnamon-spices-applets/issues/5387).

**Pull request merged**
