### PR TITLE
[scripts@paucapo.com] Added support for localizations, some minor fixes

### PR DESCRIPTION
**Pull request by muzena**

### CODE REVIEW

**Comment by muzena** [comment]
#134

**Comment by Odyseus** [comment]
Hello, @muzena.

It looks perfect to me. :+1:

A couple of notes that will help you avoid errors in the future:

- Now that you created a new branch, you can create more branches to work on other applets if you need/want to. When you were working directly on master, you couldn't do that without waiting for a pull request to be merged.
- After a pull request is merged, you can safely remove your branch (in this case, the *scripts@paucapo.com-added-localizations-and-fixes* branch). I repeat, **after the pull request is merged**.
- Always create new branches from master. To make sure that you are in master, just `git checkout master` and then create your new branch.

**Comment by NikoKrause** [comment]
@paucapo
Are you still active?

**Comment by Odyseus** [comment]
Hello, @NikoKrause.

He already [gave the OK](https://github.com/linuxmint/cinnamon-spices-applets/pull/38#issuecomment-276058788).

**paucapo said:**
> Hi all, I'm not using Cinnamon anymore, anyone can take care of this simple applet?
> 
> Thanks!

**Comment by NikoKrause** [comment]
Ah. Right. Forgot about that.

**Comment by NikoKrause** [comment]
@muzena 
Could you change the commit message? It should contain the spices name/uuid first.

**Comment by muzena** [comment]
@NikoKrause 
Is now ok?

**Pull request merged**
