### PR TITLE
Adds Mic-Tools applet

### PR DESCRIPTION
**Pull request by chaptergy**
This applet allows listening to the microphone and muting it

### CODE REVIEW

**Comment by brownsr** [comment]
I'm seeing what appears to be a coding error in your applet.js when I try this out:

Cjs-Message: 21:00:49.034: JS LOG: [LookingGlass/info] Settings successfully installed for mic-tools@chaptergy
Cjs-Message: 21:00:49.062: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function 265]: Too many arguments to method Gio.DataInputStream.read_line_async: expected 3, got 4
Cjs-Message: 21:00:49.068: JS LOG: [LookingGlass/warning] "Mic-Tools - ADDED TO PANEL"
Cjs-Message: 21:00:49.082: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function 265]: Too many arguments to method Gio.DataInputStream.read_line_async: expected 3, got 4
Cjs-Message: 21:00:49.095: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function 265]: Too many arguments to method Gio.DataInputStream.read_line_async: expected 3, got 4
Cjs-Message: 21:00:49.098: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function 265]: Too many arguments to method Gio.DataInputStream.read_line_async: expected 3, got 4

you can see the errors in the .xsession-errors file in your home directory

Regards

Simon

**Comment by brownsr** [comment]
ping @chaptergy

**Comment by brownsr** [comment]
ping @chaptergy

**Comment by chaptergy** [comment]
Sorry, I am busy with uni stuff. But, that's really weird, that would mean the cinnamon library is different on your system than it was on mine. I assume you are on the newest version?

**Comment by brownsr** [comment]
feel free to re-open when you've got to the bottom of the errors.

Regards

Simon

**Pull request closed without merging**
