### PR TITLE
pomodoro@gregfreeman.org: small bug fixes and changes

### PR DESCRIPTION
**Pull request by NikoKrause**
@gfreeau 

* Removed settings from left click menu since it's accessible through rightclick menu.
* Fix icon setting: Show/Hide icon instead of destroying the icon box
* Fix "What is this?" button: Use distro-agnostic "xdg-open" instead of "gnome-open"
* Remove emptyspace before "!"
* Let translator decide, which website to open whe you click on "What is this?"
* When showing remaining time, you need to consider the correct singular/plural for the time value: 1 minute, but 2 minutes
      Some languages have more than 1 Singular and 1 Plural, so we use dngettext now, which takes care of this.
* In Mint the 'sox' package, which is required for the sound to work, is not installed by default. Add instructions to README
* Add information label to install settings, if 'sox' is not installed
* Add yellow pomodoro icon, if the applet is not running
* Add option for symbolic icons
* Use python3 explicitly

Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/3105
Closes https://github.com/linuxmint/cinnamon-spices-applets/issues/2407

### CODE REVIEW

**Comment by gfreeau** [comment]
Hey @NikoKrause This looks pretty good. This looks to be all backwards compatible, I want all LTS versions supported back to mint 18 at least.

It would be great if you could commit a few more things in this merge. One is updating the README about python, the applet expects `python` to be on the path, but this is not always true for newer mint versions. The workaround is to install `python-is-python3` or make a symlink.

As described by users here. https://cinnamon-spices.linuxmint.com/applets/view/131

To make it easier, maybe extend the current message `Great tool for boosted productivity!` and specifically mention sox and python there to help users. I've been meaning to do this.

**Comment by NikoKrause** [comment]
Hey,

I can add the instruction to the README, but I think, it would be better to solve it explicitly for everyone:
- Change the shebang in `kill-looping-sound.py` from `#!/usr/bin/python` to `#!/usr/bin/python3`
- Change the `python` command in the `applet.js` file to `python3`

This should work without having to install `python-is-python3`.

For the `sox` package I suggest to check for `/usr/bin/sox` and show a `label` in the settings, if `sox` is missing. (<- not sure, if there is a `label` type in Mint 18).
grafik

Btw are you aware of the multiversion feature, to keep applets backwards compatible?

P.S.: I have two things, which still bug me a little bit, and another feature idea.
1. If you hide the time in the panel, so you see only the tomato, you can't see if the applet is running or not. My suggestion. Show a yellow tomato, if the applet is not running. (If you could send me a yellow version of the icon.png, I could add it to this pull request.)
2. The applet doesn't remember it's state and the time. If I restart Cinnamon, the applet turns off and resets the timer. When working on applets etc. I need to restart Cinnamon a lot, which makes this applet unusable during those programming times. Unfortunately I don't have much time during winter to work on this. Maybe you have an idea and time for that. If not, it's ok. Maybe I'll find sometime next year for that.
3. Most applets in Cinnamon use symbolic icons now. So I'd like to add on option to use symbolic icons in the panel instead of the coloured tomatoes. My suggestion for symbolic icons:
screenshot-cinnamon-2020-11-22-141507 screenshot-cinnamon-2020-11-22-141540 screenshot-cinnamon-2020-11-22-141615
There's even an option to colourize the symbolic icons to green and red as the battery applet does:
screenshot-cinnamon-2020-11-22-142745

**Comment by gfreeau** [comment]
Hey, here's an icon you can use to try out your idea when hiding time: https://www.gregfreeman.io/files/icon-running.png


Unfortunately I don't have time to do the things you requested at the moment, but I agree with all of them such as saving the state in a simple file in case or reload.

For now, happy to merge all of this as long as it doesn't break compatibility for versions earlier than 20. The multiversion feature will be helpful. My only concern is simply changing to python3, older LTS versions don't have it as default I believe?

**Comment by NikoKrause** [comment]
Thanks for the icon. I'll try it next weekend probably. Also need to check compatibility with Mint 18 then.

**Comment by NikoKrause** [comment]
Ok, I implemented the changes. 
Everything seems to work fine in Mint 18 and Mint 19.3.

**Comment by gfreeau** [comment]
Hey @NikoKrause I tested it on 18 LTS versions and it works great, so happy to get this merged.

Suggestion though, instead of

`Please install 'sox' and restart Cinnamon to use the sound feature!`

I would recommend

`Please install the packages 'sox' and `python3` then restart Cinnamon to use the sound feature!`

I'm pretty sure python3 is not a default package in older mint versions.

Otherwise great! thanks a lot for your work.

**Comment by gfreeau** [comment]
After another look, might be better to duplicate the message completely for `python3` since I see you are checking if the package is installed before showing the message.

**Comment by NikoKrause** [comment]
Python3 is installed by default in Mint 18

**Comment by gfreeau** [comment]
Awesome, then this is good to merge, thanks a lot for taking the time and effort.

**Pull request merged**
