### PR TITLE
bumblebee@marmistrz: remove applet

### PR DESCRIPTION
**Pull request by NikoKrause**
@marmistrz following the discussions [here](https://github.com/linuxmint/cinnamon-spices-applets/pull/450#issuecomment-322692516), the features of this applet have been adapted to the bumblebee@pdcurtis applet

### CODE REVIEW

**Comment by marmistrz** [comment]
Go ahead :)

**Comment by melmelissa** [comment]
Unfortunately this applet
Https://github.com/pdcurtis/cinnamon-applets/tree/master/bumblebee%40pdcurtis    dysfunctional at home.

When using my Nvidia, I have jerks, which triggers freezes on the software I use (darktable, blender, pitivi in particular) :(
Or a simple ### optirun glxspheres64, causes the serrated wheels to jerk.
Yet my pc is powerful ...

While the old simple applet has never put me worries of this kind, hence the fact that I regret it ...

**Comment by marmistrz** [comment]
You seem to be using some old version, bumblebee@pdcurtis has been updated lately: https://cinnamon-spices.linuxmint.com/applets/view/167

**Comment by melmelissa** [comment]
Of the blow with a manual installation of the applet, indeed the problem seems solved, optirun glxspheres64 does not bug anymore.
The temperature is displayed correctly, something I did not have before.

And your applet is also functional, I had not put it in the right folder (it's not good heat wave for neurons :D

Sorry for my English, I am French.
I'm glad that both applets are working, so it's the basis of your applet that was used to form the new one.??
The two are complementary.??

**Pull request merged**
