### PR TITLE
[MuteToggler@jebeaudet.com] Removes other occurance 'TextDecoder'

### PR DESCRIPTION
**Pull request by sphh**
See https://github.com/linuxmint/cinnamon-spices-applets/issues/3979#issuecomment-1813196790

### CODE REVIEW

**Comment by claudiux** [comment]
Please consider creating a new, updated branch for these changes.

**Comment by rcalixte** [comment]
cc @jebeaudet

**Comment by jebeaudet** [comment]
I've opened #5101 which has a clean branch and the missing toString(). We can close this one Thanks

**Comment by sphh** [comment]
Thanks @jebeaudet !!

**Pull request closed without merging**
