### PR TITLE
weather@mockturtl Update 2.3.7

### PR DESCRIPTION
**Pull request by Gr3q**
Changes:
* Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/2816, changed to different geolocation API
* Fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/2808
* Debug can be enabled by placing a file named DEBUG to the applet folder
* Added complete TS declaration files for some import modules (the easy ones...)
* Only import whats needed (hopefully it speeds loading the applet the first time, but I don't really know)

### CODE REVIEW

**Comment by Gr3q** [comment]
What version of Cinnamon this style of importing came in, does anyone know?
```Javascript,
var {aaa, bbb} = imports.gi.etc;
```

**Comment by Odyseus** [comment]
Hello, @Gr3q.

That's called [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) and it doesn't depend on a Cinnamon version, but in a SpiderMonkey version (Firefox). For all intent and purposes, you can use it in all Cinnamon versions in existence (from 3.0.x onwards).

**Comment by Gr3q** [comment]
Hey @Odyseus 
Thanks, that's good news, meaning I can use it and still keep one codebase for both versions

**Comment by Gr3q** [comment]
@brownsr Hold on merging this, its non-functional at the moment

**Comment by Gr3q** [comment]
@brownsr All good now, tested as well on Cinnamon 3.0

**Comment by brownsr** [comment]
What are the implications of these .ts files ?  Is there an implied dependency with versions of the glib etc. libraries that needs to be managed ?  They look generated to me with all that whitespace, is that right ?  if so what commands and scripts are being used - that will need some sort of basic documentation if so so others can make changes.

Regards

Simon

**Comment by Gr3q** [comment]
So ok, I can put some documentation in there, but I'll explain now as well.

Purpose of the files:
These are Typescript declaration files (.d.ts), simply describing libraries already present in (my and probably every) system whats using Cinnamon. They help with static type checking and get offered in autocomplete, they are never transpiled into JS.

**They are optional.** I  - or anyone - could just as well remove them and declare ```imports: any``` but then I would have to look up documentation all the time. It gives me a head start how to use the libraries.

File versions:
Simply these versions were present on my system. I don't think the call signatures change that much, anyway its better to be explicit about those.  

File generation:
 I used my fork of [GIR2TS](https://github.com/Gr3q/GIR2TS), It generates Typescript declarations from from .gir files. They are included in the _gobject-introspection_ package.

It is far from perfect (Typescript can't handle overloaded functions for example), especially with libsoup and some other libraries, but it is much better to read these than the .gir files or the GTK documentation.  Wish I had time make it include the docstrings too.

**Pull request merged**
