### PR TITLE
Add Chinese translation for Printers

### PR DESCRIPTION
**Pull request by giwhub**
Add Chinese translation for Printers.

### CODE REVIEW

**Comment by collinss** [comment]
@linux-man

**Comment by linux-man** [comment]
Fine by me! Is it necessary to update LINGUAS? I was never certain if that file was used on some installation script or not.

**Comment by collinss** [comment]
As far as we have been able to determine, the LINGUAS file is not needed, and does nothing.

**Comment by linux-man** [comment]
Thanks. Could you please remove LINGUAS file?

**Comment by collinss** [comment]
Sure

**Comment by collinss** [comment]
https://github.com/linuxmint/cinnamon-spices-applets/commit/43134154b1ccca11a1723dc4ac38eda86227f64d

**Pull request merged**
