### PR TITLE
SpicesUpdate@claudiux: v1.2.0 - Fixes #2230

### LINKED ISSUE #2230: [SpicesUpdate@claudiux] Open cinnamon applet (desklet/extension/theme) page on Download tab
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json") 1.1.3
 * Cinnamon version (cinnamon --version) 4.0.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 ```

**Notify author of applet**
@claudiux 

**Issue**
You already mentioned this in https://github.com/linuxmint/cinnamon-spices-applets/pull/2165#issuecomment-450722762: It would be great, if the menu entry opens the cinnamon applet (desklet/extension/themes) page in the `download` tab and in `date` order. Is that possible?

### PR DESCRIPTION
**Pull request by claudiux**
Hi @jaszhix,

This PR fixes #2230. To do this, I used and modified a copy of `/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py`. I hope that will be accepted.

Best regards.
Claudiux

### CODE REVIEW

**Comment by claudiux** [comment]
Using `diff --suppress-common-lines open_download_tab.py /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py`:
```
2,4d1
< # This is a palimpsest of /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py (Cinnamon 4.0.9)
< # made to open the Download tab with spices sorted by date.
< # Usage: ~/.local/share/cinnamon/applets/SpicesUpdate@claudiux/scripts/open_download_tab.py applets|desklets|extensions|themes
17d13
< sys.path.append("/usr/share/cinnamon/cinnamon-settings")
143,148c139
<                     if len(l) > 1: # claudiux
<                         sidePage.stack.set_visible_child(l[1]) # claudiux
<                         sidePage.stack.get_visible_child().sort_combo.set_active(2)
<                         sidePage.stack.get_visible_child().sort_changed()
<                     else: # claudiux
<                         sidePage.stack.set_visible_child(l[0])
---
>                     sidePage.stack.set_visible_child(l[0])
```

**Comment by jaszhix** [comment]
I'm not sure forking parts of Cinnamon is the best solution here. Why not PR a change in cinnamon so the settings pages can be controlled from the cli?

**Comment by claudiux** [comment]
That's my intention. But these changes in Cinnamon will only be valid in v4.2, it seems to me?

This is only a transient solution to solve the issue #2230.

**Comment by jaszhix** [comment]
Cool. I just think its a drastic step for a minor inconvenience to the user. E.g., you'd have to maintain a core part of Cinnamon in your extension.

**Comment by claudiux** [comment]
It does not scare me. ;)

And I can make this applet multi-version.

**Comment by claudiux** [comment]
Hi @jaszhix,

Could you merge this PR with your master branch, please?

**Comment by jaszhix** [comment]
I don't think this should be merged in its current state. If more applets start borrowing and re-purposing cinnamon components to get features out quicker it can become a maintenance burden when bugs are found in cinnamon.

**Comment by clefebvre** [comment]
Well, there's nothing wrong with adding the ability to open a particular tab and follow a particular sorting order in cinnamon-settings. We can do that in 4.2. I'm not sure I like the way the arguments are defined (1, 2, etc... that's not very explicit, but anyway that's a detail).

Once that's done, from a an applet dev point of view, you need to accept that this feature is only present in 4.2 onward and not before. The applet can have a 4.2 dir and behave differently from that version on.

**Comment by claudiux** [comment]
@clefebvre @jaszhix Is it now acceptable? The latest changes no longer require any changes in `/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py` and result in easier maintenance of this applet.

I can also close https://github.com/linuxmint/Cinnamon/pull/8333 or modify it to change parameters in --tab=1 --sort=2.

**Comment by jaszhix** [comment]
Yeah, LGTM. Just to clarify, I was only talking about this PR in particular. I understand where you're coming from, and don't blame you for wanting to add it in there.

**Comment by claudiux** [comment]
Many thanks @jaszhix !

I should have offered this code immediately. I admit to having wanted to go faster, without thinking too much. It was you who were right.

**Comment by French77** [comment]
@claudiux Handsome found.:+1:

Applet Spices Update has become very complete with these improvements,thank you for this

**Pull request merged**
