### PR TITLE
location-detection@heimdall: add ability to set API key in Settings

### PR DESCRIPTION
**Pull request by NikoKrause**
@heimdall
Added settings to applet, so the user can easily register on IPInfoDB and set/use his own API key.
And updated translation files.

### CODE REVIEW

**Comment by NikoKrause** [comment]
@BrainAxe
Are you using this applet and do you have a valid API-key? If yes, can you check this version. I'm too lazy to register on IPInfoDB ;)

**Comment by BrainAxe** [comment]
@NikoKrause 
Thanks for asking. I am still using this applet and I tested this piece of code with my valid API-key. I think this is a nice update. I am giving some screen-shot of the testing .
screenshot_00000
screenshot_00002
screenshot_00001

**Comment by NikoKrause** [comment]
Thanks for testing

**Comment by NikoKrause** [comment]
This applet is abandoned, the author does not respond and author was set to `none`.
So I'm going to merge this.

**Pull request merged**
