### PR TITLE
Screenshot+record desktop@tech71 fix

### PR DESCRIPTION
**Pull request by muzena**
Fix Videos and Pictures folder not opening, fix recording scripts, new screenshot.png

### CODE REVIEW

**Comment by clefebvre** [comment]
@tech71

@muzena no need to add the version field in the metadata.

**Comment by muzena** [comment]
Ok, removed.

**Comment by NikoKrause** [comment]
@clefebvre 
There is no github user tech71

**Comment by NikoKrause** [comment]
Since this applet has no author, I'm gonna merge this

**Pull request merged**
