### PR TITLE
cinnamon-spices-applets: Update readme

### PR DESCRIPTION
**Pull request by claudiux**
Adds how to determine the expiration date of a Linux Mint version.

### CODE REVIEW

**Comment by rcalixte** [comment]
Just a few thoughts:
* This doesn't cover LMDE or other distros.
* Applets (and Spices) themselves are meant to work anywhere so it feels out of place here to call this out.
* Why this instead of the Wikipedia page for Mint which has the benefit of being maintained release by release?

I don't mean to heap things on so apologies if it feels that way.

**Comment by claudiux** [comment]
>     * This doesn't cover LMDE or other distros.

I'm not the author of this table.
 
>     * Applets (and Spices) themselves are meant to work anywhere so it feels out of place here to call this out.

The authors of Spices are therefore obliged to maintain them for all versions of Cinnamon, even those that have expired?

>     * Why this instead of the Wikipedia page for Mint which has the benefit of being maintained release by release?

We should at least provide a link to this Wikipedia page.

> I don't mean to heap things on so apologies if it feels that way.

Well, one time more or less... I don't feel like offering anything anymore.

**Comment by fredcw** [comment]
I think it would best to just mark the unsupported mint versions in the table. I'm at work atm, but I can do this later. I guess it's up to applet maintainers if they want to support older versions.

**Comment by rcalixte** [comment]
> I think it would best to just mark the unsupported mint versions in the table. I'm at work atm, but I can do this later. I guess it's up to applet maintainers if they want to support older versions.

Are the first two columns even needed? What matters is the version of Cinnamon and the underlying JS engine right? It would also make it easier to maintain long-term. (I also think the Cinnamon Version column only needs the major and minor.)

**Comment by fredcw** [comment]
@rcalixte I think the mint version is useful, codename not so much. But in any case, I think it's handy to have this here as the only other place it's documented is wikipedia. The shipped stable cinnamon version is not documented anywhere else afaik.

**Comment by rcalixte** [comment]
> @rcalixte I think the mint version is useful, codename not so much. But in any case, I think it's handy to have this here as the only other place it's documented is wikipedia. The shipped stable cinnamon version is not documented anywhere else afaik.

Wouldn't someone looking for this info on their system check the System Info dialog? Granted, all of that information is there, but the Cinnamon version is what matters, not the distro. (I have been looking at this through the lens of the table being useful to anyone using Cinnamon, not necessarily just Mint users. Let me know if that's incorrect since I think that's the reason we see this slightly differently.)

**Comment by rcalixte** [comment]
I'm thinking that we only need three columns here. (Correct me if I'm wrong.)

|Cinnamon<br />Version|Release<br />Date|CJS<br />Version|
|:-:|:-:|:-:|
|6.0.x|12 Jan 24|102|

**Comment by fredcw** [comment]
@rcalixte Actually, since I made it, I've barely used it for its stated purpose. I use it quite often to see which cinnamon version goes with which Mint version. For instance, when communicating with users, I find it better to write "cinnamon 4.8 (Mint 21.1)" rather than just the cinnamon version and this information isn't really available anywhere else. In any case, I don't see the harm in keeping this info here in case anyone finds it useful.

**Pull request closed without merging**
