### PR TITLE
Updated translations for various applets

### PR DESCRIPTION
**Pull request by bossbob88**
Hello everyone,

I updated the hu.po translation file for various applets. Some were incomplete, therefore the update.

### CODE REVIEW

**Comment by NikoKrause** [comment]
This PR has conflicts.

**Comment by bossbob88** [comment]
Hi!

Asou can see in the conflicting lines, the previous/master versions of the conflicting hu.po files did/do not have Hungarian translations. My pull request would add these missing translations. I don't see what else would be conflicting with my pull request.
If it cannot be added to the master repo, then just  let me know annd I can delete these three conflicting hu.po files, since they contain really tiny additions to the Hungarian translations and can be ignored if necessary.

**Comment by brownsr** [comment]
With this many translation files, it would seem easier to just delete the three problematic ones, and come back to them in another PR.

Regards

Simon

**Comment by bossbob88** [comment]
I agree with you Simon!

Could you please delete the files, as you did during a previous conflict or should I do it?

**Comment by bossbob88** [comment]
I deleted  the conflicting files!

**Comment by brownsr** [comment]
I had to do some manual conflict resolution.  Best check the results are as you expect.  Suggest you ensure your master is up to date before you do more (git fetch upstream   git merge upstream/master     say) and I'd really recommend branching before making changes, and PRing the branch.  Working off master can create awkward situations to fix when errors are made, which we all do from time to time.

Regards

Simon

**Comment by bossbob88** [comment]
Many thanks again for  the  help and advice Simon!

**Pull request merged**
