### PR TITLE
[radio@driglu4it] HOT FIX - Fix config not working on fresh install

### PR DESCRIPTION
**Pull request by jonath92**
In the last pr I have accidentally used `ur` instead of `url`. This lead to a type Error each time the applet makes some changes in the settings for new users (which is very often the case and makes the applet almost useless for new users). 

@brownsr when possible please accept this soon. There are just very few changes.

### CODE REVIEW

**Comment by fredcw** [comment]
The applet description in the applets dialog is still "A simple radio applet for cinnamon". Maybe this undersells it a little bit now? How about "A radio applet with 1000's of searchable stations" or something similar?

Also, I just tried removing and reinstalling the applet but the download dialog didn't appear, only a notification "Couldn't start the applet. Make sure mpv..." I don't remember doing this last time. Is this intended? I'm using manjaro.

**Comment by jonath92** [comment]
@fredcw yes that's a good idea. I will Update the description in the next Version.

Currently mpv only gets installed automatically on Systems with apt but I agree that it would be nice to also handle pacman

**Comment by fredcw** [comment]
That's strange, I sure it installed it automatically last time. And how would apt install .mpris.so into ~/.cinnamon/configs anyway? And pacman wouldn't help with that either. I would have thought that you would download it directly from https://github.com/hoyon/mpv-mpris/releases/download/0.6/mpris.so and that that would work on any distro?

**Comment by jonath92** [comment]
Ah ok I see what you mean. There are two Dialogs - one for installing mpv and one for the mpris plugin. And the mpris plugin indeed should be downloaded on any distro. I am currently just on the Smartphone so I can't test but I don't see any reason in the Code why it should not work. I will look into it in more detail tomorrow.

**Comment by jonath92** [comment]
@fredcw it definitely works on Linux mint. No idea why it doesn't work on manjaro. I will test it on manjaro tomorrow.

**Pull request merged**
