### PR TITLE
[Cinnamenu@json] Performance improvements

### PR DESCRIPTION
**Pull request by fredcw**
+ created new class for header text (.menu-applications-header-text)

### CODE REVIEW

**Comment by fredcw** [comment]
Not sure why All checks failed?

**Comment by NikoKrause** [comment]
This seems to be a temporary issue with GitHub Actions.
I saw this once. Maybe a server issue.

**Comment by fredcw** [comment]
Ok thanks, I updated the pot file anyway, and there was one string that was different that I forgot about. Maybe it was that?

**Comment by NikoKrause** [comment]
No, I had the same issue in the desklet repo. How did you update the potfile? I'm wondering, because all the comments are gone.

**Comment by fredcw** [comment]
Yeah, I usually delete all the comments because I think it saves a lot of space, less than half the size. It's just a quick regex replace. I wonder though if the comments are useful to the translators and maybe should be kept?

**Comment by NikoKrause** [comment]
Some comments can be useful.

**Pull request merged**
