### PR TITLE
stevedore@centurix: Add a Docker applet to the Cinnamon Applet Spices repository

### PR DESCRIPTION
**Pull request by Centurix**
This is a new applet for the Cinnamon Applet Spices repository that adds Docker image and container support to the panel. Docker images can be searched for and pulled directly from Dockers image store, and containers configured and independently controlled from this menu item.

I've made the assumption that new additions to this repo must have the file structure setup in the same way with an info.json (I added my Github username), screenshot.png, icon.png and the README.md in the root while the main applet in the files/stevedore@centurix folder. Let me know if this is incorrect. Thanks!

### CODE REVIEW

**Comment by NikoKrause** [comment]
Structure seems OK to me. You can create a symbolic link `stevedore@centurix/README.md`, which has the target `stevedore@centurix/files/stevedore@centurix/README.md`.

This way you don't have to always copy the README.md file, if you change it.

**Comment by jaszhix** [comment]
I tested on Cinnamon 3.4 and ran into a start up crash.

```sh
error t=2017-06-23T08:04:12.567Z mounts[0] is undefined
trace t=2017-06-23T08:04:12.568Z 
<----------------
Stevedore.prototype.refreshMenu@/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js:550:24
Stevedore.prototype._init@/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js:461:9
Stevedore@/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js:430:5
main@/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js:782:12
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:409:18
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:298:22
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:60:18
loadExtension@/usr/share/cinnamon/js/ui/extension.js:451:17
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:236:13
---------------->
```
As a heavy Docker user, I really like the idea of more options for managing images and containers. Hopefully the stack trace helps.

**Comment by Centurix** [comment]
Give this a try, most of my containers have mount points. I think I overlooked containers without. Very interested to get feedback on this applet as I'd have to admit it's a bit skewed towards my personal usage. :)

**Comment by brownsr** [comment]
Never used docker in my life, so I am quite a naive tester for this.  I installed docker CE, but I did not do the additional post-installation steps to set up a docker group to avoid having to use sudo.  On trying to install my first image (hello-world)  the applet appeared to work OK, but nothing got installed, and the log was full of error messages.  I suspect that I would need to set up the docker group. 

Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 116]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 118]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 119]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 121]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 123]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 125]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 127]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 129]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 132]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 47]: assignment to undeclared variable output_lines
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 25]: assignment to undeclared variable row
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 26]: assignment to undeclared variable last_reduction
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 31]: assignment to undeclared variable positions
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 49]: assignment to undeclared variable columns
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 50]: assignment to undeclared variable lines
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/applet.js 476]: assignment to undeclared variable images
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/applet.js 515]: assignment to undeclared variable containers
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/applet.js 618]: assignment to undeclared variable dialog
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/applet.js 342]: assignment to undeclared variable searchTerm
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/applet.js 347]: reference to undefined property this._timer
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/applet.js 405]: assignment to undeclared variable temp_note
Cjs-Message: JS LOG: Invalid or null source id used when attempting to run Mainloop.source_remove()
== Stack trace for context 0x555ef1bf3020 ==
overrideMainloop/Mainloop.source_remove@/usr/share/cinnamon/js/ui/overrides.js:114:13
NewImageDialog.prototype._onKeyPressEvent@/home/simon/.local/share/cinnamon/applets/stevedore@centurix/applet.js:348:17

Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/applet.js 373]: assignment to undeclared variable index
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.27/images/create?fromImage=dockercloud%2Fhello-world&tag=latest: dial unix /var/run/docker.sock: connect: permission denied

**Comment by jaszhix** [comment]
Cool. I think this issue has to do with Cinnamon 3.4 using a newer JS interpreter. I am seeing strict mode warnings in .xsession-errors.

```sh
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 116]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 118]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 119]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 121]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 123]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 125]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 127]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 129]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 132]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 47]: assignment to undeclared variable output_lines
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 25]: assignment to undeclared variable row
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 26]: assignment to undeclared variable last_reduction
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 31]: assignment to undeclared variable positions
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 49]: assignment to undeclared variable columns
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 50]: assignment to undeclared variable lines
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 52]: assignment to undeclared variable line
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js 476]: assignment to undeclared variable images
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js 488]: assignment to undeclared variable menu_index
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js 515]: assignment to undeclared variable containers
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js 526]: assignment to undeclared variable status_tokens
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 211]: assignment to undeclared variable container
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js 547]: assignment to undeclared variable mounts
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js 550]: reference to undefined property mounts[0]
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 116]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 118]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 119]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 121]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 123]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 125]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 127]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 129]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 132]: can't assign to arguments in strict mode
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js 551]: reference to undefined property mounts[0]
```
It looks like in [newContainer](https://github.com/Centurix/cinnamon-spices-applets/blob/d6afc1f4650db5ee704131c106a7db250da5b250/stevedore%40centurix/files/stevedore%40centurix/docker.js#L114) you are using arguments as a string, but arguments is a reserved keyword holding an array of the function's arguments.

**Comment by Centurix** [comment]
Ah, OK, I'm not currently on Cinnamon 3.4, but I've added the correct scoping for newer Javascript, removed keyword re-use and a minimum Docker version check. I'll probably setup a 3.4 install and give it a test, but this commit should get it there. Thanks for the feedback @jaszhix  @brownsr @NikoKrause

**Comment by brownsr** [comment]
I did the docker recommended post install steps so as to eliminate any potential issues around sudo etc.

The applet is crashing on startup:

```shell
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 56]: assignment to undeclared variable line
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/applet.js 566]: reference to undefined property mounts[0]
```

**Comment by brownsr** [comment]
Well as far as I can tell knowing nothing about docker it appears to be generally working now.  
I did trigger some log errors, I think the snippet below was when I deleted a container
```shell
(cinnamon:2580): Cjs-WARNING **: JS ERROR: Exception in callback for signal: activate: TypeError: GLib.spawn_command_line_async(...)[Symbol.iterator] is not a function
Docker.prototype.removeImage@/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js:86:40
Stevedore.prototype.removeImage@/home/simon/.local/share/cinnamon/applets/stevedore@centurix/applet.js:672:9
_emit@resource:///org/cinnamon/cjs/modules/signals.js:142:27
PopupBaseMenuItem.prototype.activate@/usr/share/cinnamon/js/ui/popupMenu.js:177:9
PopupBaseMenuItem.prototype._onButtonReleaseEvent@/usr/share/cinnamon/js/ui/popupMenu.js:150:9
```

I would suggest sorting out those stevedor/stevedore inconsistencies

**Comment by jaszhix** [comment]
It loads for me now as well, and lists all of the images and containers in use on my system. When expanding items under the containers section, there doesn't seem to be any sub-menu items, the arrows just point down. I saw this stack trace repeat several time before the applet did launch, I'm guessing it still worked because it was caught in a try-catch block.

glass.log:

```sh
trace t=2017-06-23T19:53:53.782Z 
<----------------
Docker.prototype.IPAddress@/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js:195:13
Stevedore.prototype.refreshMenu@/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js:577:1
Stevedore.prototype._init@/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js:476:9
Stevedore@/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js:433:5
main@/home/jason/.local/share/cinnamon/applets/stevedore@centurix/applet.js:803:12
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:409:18
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:298:22
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:60:18
loadExtension@/usr/share/cinnamon/js/ui/extension.js:451:17
onEnabledAppletsChanged@/usr/share/
```
.xsession-errors:

```sh
Cjs-Message: JS WARNING: [resource:///org/cinnamon/cjs/modules/tweener/tweener.js 547]: reference to undefined property properties[istr].isSpecialProperty
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 195]: reference to undefined property container.NetworkSettings.Networks.bridge
Cjs-Message: JS WARNING: [/usr/share/cinnamon/js/ui/popupMenu.js 2025]: reference to undefined property actor._delegate
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/stevedore@centurix/docker.js 195]: reference to undefined property container.NetworkSettings.Networks.bridge

```

I could see this being really useful. Are the menu items supposed display some of the data you would see in ```docker ps```? I would remove all the try-catch blocks and see if you can get it working without them. Good job so far, I like where its going. :)

**Comment by Centurix** [comment]
Got a Cinnamon 3.4 install happening and found the async issue reported by @brownsr , @jaszhix  I can see the issue with garnering the IP address from the container and I'm pretty sure it's to do with the network setup in the container itself, I've pushed up a fix as the code was assuming the networking to always be in bridging mode.

**Comment by Odyseus** [comment]
Hello, everybody.

@Centurix: A little suggestion. Use a text editor with a JavaScript *linter*. Otherwise, you will spend a lot of time fixing *errors* that could have been avoided. Like the following *error* from your last commit. The following images are from Sublime Text with the **SublimeLinter** plugin and from Atom with the **linter** plugin. Both plugins from both text editors uses **jshint** as their *linter*.

lintersuggestion

lintersuggestion2

I would recommend Sublime Text over Atom, because Atom is slow as hell.

**Comment by brownsr** [comment]
The .xsession-errors from a run after your most recent changes.  I pulled in a hello-world image, created a container, turned it on, then turned it off and removed it.
```shell
Cjs-Message: JS WARNING: [/home/simon/.local/share/cinnamon/applets/stevedore@centurix/docker.js 195]: assignment to undeclared variable last_ip

(cinnamon:2805): libnm-glib-WARNING **: async_got_type: could not read properties for /org/freedesktop/NetworkManager/Devices/5: No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/Devices/5

(cinnamon:2805): libnm-glib-WARNING **: async_got_type: could not read properties for /org/freedesktop/NetworkManager/Devices/5: No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/Devices/5

(cinnamon:2805): libnm-glib-WARNING **: async_got_type: could not read properties for /org/freedesktop/NetworkManager/Devices/7: No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/Devices/7

(cinnamon:2805): libnm-glib-WARNING **: async_got_type: could not read properties for /org/freedesktop/NetworkManager/Devices/7: No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/NetworkManager/Devices/7
```

**Comment by brownsr** [comment]
@centurix What would you prefer ?  We can iterate this a little more before merging, or we can merge and let the minor issues get sorted afterwards.  As I suspect quite a few people will want to try this, then the cleaner you get it up front the fewer issues are likely to get raised.  But merging it also makes it possible for others to put their own PRs in to fix bugs, which you may think is useful to you.  So any preference ? From my perspective we've checked it over for malicious or destructive code, it fits the naming and file structure, and it appears to function and doesn't break Cinnamon, so it can be merged.

**Comment by Centurix** [comment]
@brownsr I feel like I'm making progress with the Javascript upgrade, this last commit made a flurry of changes in that direction. The async_got_type warnings seem to relate to Docker and I'm going to try to nail those down, but I'm happy with a merge at this point as I'll be actively modifying and fixing this component. @Odyseus Thanks for the JSHint tip, that helped me out a great deal, although for some reason it wouldn't pick up the scoping declarations, but it did pick up quite a few other issues that I've resolved with this commit. Thanks again to all.

**Pull request merged**
