### PR TITLE
[better-backgrounds@simonmicro] Add support for libsoup3

### PR DESCRIPTION
**Pull request by fredcw**
Add support for libsoup3. For more info see https://github.com/linuxmint/cinnamon/commit/76224fe409d074f8a44c70e4fd5e1289f92800b9

@simonmicro

### CODE REVIEW

**Comment by simonmicro** [comment]
Thanks for your work - I'll merge it also into my branch / upstream, if it works :grin:

**Comment by DRR0B0T** [comment]
URI does't work check it in http://source.unsplash.com/ , i see it in your source code. Change your uri to the uri wich works pls.

**Comment by fredcw** [comment]
Just to be clear, the issue mentioned by @DRR0B0T is not related to this PR as this PR makes no changes to any of the urls used by the applet. I've tested this PR with both soup 2.4 and 3.0 and it all seems to work fine.

Having said that, @DRR0B0T , the unsplash url you mentions seems to work for me in the applet as it is although it does seem quite slow to respond (about 4-5 seconds), I'm in the UK if that makes a difference? Perhaps open a new issue for this, as it's not related to this PR?

**Comment by simonmicro** [comment]
@DRR0B0T This does not seem right. Could you share the URI you have tried and does not work for you? It will be logged on the console. If it fails for multiple people, it may seem worth investigating...

@fredcw Thanks for your work!

**Comment by DRR0B0T** [comment]
@simonmicro This http://source.unsplash.com/.

**Comment by DRR0B0T** [comment]
@fredcw At now it working normally, but downloading works with biggest timeout. Linux Mint Cinnamon 21

**Comment by simonmicro** [comment]
@DRR0B0T Moved to here: https://github.com/simonmicro/better-backgrounds/issues/22

**Pull request merged**
