### PR TITLE
jenkins@backuity.org: Handle other build statuses from Jenkins, such as disabled and aborted

### PR DESCRIPTION
**Pull request by vitaliis**
Previously everything which wasn't a success was displayed as a failure.
This was incomplete as there are other statuses for jenkins jobs possible.
This commit makes it possible to differentiate between failed and disabled jobs

### CODE REVIEW

**Comment by vitaliis** [comment]
@clefebvre PR available. According to guidelines you should be notified

**Comment by collinss** [comment]
@vitaliis Actually, the one you should notify is the author of the applet. In this case it is @backuitist.

**Comment by vitaliis** [comment]
Ah, right. The "Initial commit" was done by clefebvre, but as ` cinnamon-spices-applets/jenkins@backuity.org/info.json` states the author is @backuitist.
So now he should be notified as well :slightly_smiling_face:

**Comment by backuitist** [comment]
@vitaliis: @collinss is right, could you create a PR against this repo instead: https://github.com/backuity/cinnamon-jenkins-applet

**Comment by vitaliis** [comment]
@backuitist done. https://github.com/backuity/cinnamon-jenkins-applet/pull/9

**Comment by collinss** [comment]
I'm going to close this since the pr has been moved to the other repo.

**Comment by vitaliis** [comment]
Ok. And what is the procedure for merging it to `cinnamon-spices-applets`? Should the author of the applet request the merge?

**Comment by collinss** [comment]
@vitaliis My guess is that @backuitist wants to maintain it on his own repository, and will update it himself here when he is ready. Several of the applet devs are working like that atm.

**Comment by backuitist** [comment]
@collinss @vitaliis Sorry, for the trouble, I didn't follow the change on cinnamon spices. So it seems that publishing is now done via this repo. As I told @vitaliis I'm not using/maintaining this applet anymore so I gladly hand this over to @vitaliis

**Comment by vitaliis** [comment]
@backuitist Thank you. I am ready to take it over. I am going to sleep now. But tomorrow I will post couple of changes from my work's laptop.

**Comment by collinss** [comment]
@vitaliis In that case should I reopen this, or will you open a new pr instead?

**Comment by vitaliis** [comment]
@collinss I collected all the changes and opened a new PR here: https://github.com/linuxmint/cinnamon-spices-applets/pull/187

**Pull request closed without merging**
