### PR TITLE
weather@mockturtl 3.4.0

### PR DESCRIPTION
**Pull request by Gr3q**
Changes:
* Fix https://github.com/linuxmint/cinnamon-spices-applets/issues/5212 
* Fix https://github.com/linuxmint/cinnamon-spices-applets/issues/5392
* Resolve https://github.com/linuxmint/cinnamon-spices-applets/issues/5355 - Use GeoClue as primary source for autolocation, fall back to Internet services
* Add description to Manual location entry
* Fix Saving Logs button not included the redacted config
* Update types for applet
* Use fedora geoip project for autolocation via the internet

TODO: 

- [x] Update Changelog
- [x] Test with Cinnamon 3.8
- [x] Test on Linux Mint 21.3 (with DNS timing issue on boot) - could not replicate, so this was useless

### CODE REVIEW

**Comment by sagon53** [comment]
Test unter Linux Mint 21.3 (mit DNS-Timing-Problem beim Booten) – konnte nicht repliziert werden, daher war dies nutzlos 

Auf Deutsch er  lässt die leute einfach mit dem bug hängen

**Comment by Gr3q** [comment]
@sagon53 I went to google translate with the hopes that someone tested my fix so I will know it will work or I need to work on it more. I was a bit disappointed.

On this not this is just _how much_ free time I have on my hands nowadays. It is clearly not ideal but I can't do much about it.

**Comment by rcalixte** [comment]
> @sagon53 I went to google translate with the hopes that someone tested my fix so I will know it will work or I need to work on it more. I was a bit disappointed.
> 
> On this not this is just _how much_ free time I have on my hands nowadays. It is clearly not ideal but I can't do much about it.

I'm sure the community is entirely grateful for your contributions, even if not vocal about it. The number of issues shows how popular and meaningful this applet is but popularity is definitely a double-edged sword. Thank you for taking the time to sort this out!

**Review by rcalixte — APPROVED** [review]

**Comment by st4r-w4rs** [comment]
> @sagon53 I went to google translate with the hopes that someone tested my fix so I will know it will work or I need to work on it more. I was a bit disappointed.
> 
> On this note this is just _how much_ free time I have on my hands nowadays. It is clearly not ideal but I can't do much about it.

Nice work there mate I am very thankful for your work and that you managed to fix this issue, and please don't be disappointed, I'm also sure that the whole community is grateful, I myself tried to clone and test this before the pull was done, but I wasn't sure if I'm doing it right, so I didn't wanted to review with false positives to make some nasty chaos here <3
 But overall, thanks for this great applet, it's at the top for a good reason: You're doing a great job, be proud of yourself.

_"Remember…the Force will be with you, always."_

**Comment by BillyCroan** [comment]
I appreciate you @Gr3q!

Your thoughtful weather applet is used by tens of thousands of people, every day, all day.  It's one of the few pieces of software that is always visible.  In front of me any time I'm using the computer.  Firefox can't say that.  Terminal, Libre Office, Kernel, OpenSSH,  I'm thankful all of those exist, those aren't always visible. 

Your applet is always there, for tens of thousands, every day, reminding us there's a world outside of the 1920x1200 pixels that confine our work on the computer.  

Thank you Attila, You make the world a better place for many!

**Comment by UltiWebAlt** [comment]
@Gr3q you jumped right on this and got the fix out quickly. We all very much appreciate your hard work!!!

**Pull request merged**
