### PR TITLE
Change calls to python to /usr/bin/python

### PR DESCRIPTION
**Pull request by Siphalor**
As discussed in #4331, it probably makes more sense to call to `/usr/bin/python` or `/usr/bin/python3` directly, instead of letting the `PATH` decide the python binary to use.

The main argument is that applets usually recommend/require certain apt `python-something` packages to be installed, which always target the python system installation at `/usr/bin/python`, while the user may choose to prefer another installation for most non-system use cases.

*I have only tested the color-picker applet, as this change should be pretty straight-forward.*
Someone should still look over this and check if I accidentally broke anything.

As mentioned in #4331, I would completely understand if this is deemed to be only a minor edge case.

---

Not sure if I should mention every applet author that is concerned :thinking: 

---

It should probably be considered to look for other binaries that are invoked similarly in this repository.
I chose to focus on python because of simplicity and because the `color-picker` was my main concern.

### CODE REVIEW

**Comment by fredcw** [comment]
I'll ping them just in case. @mchilli @joka42 @icarter09 @jake1164 @lauritsriple @gfreeau @jonath92 @jerrywham @cardsurf @Gr3q

**Review by Gr3q — APPROVED** [review]
> Just an idea: maybe it would be better to declare a global variable containing the python path

That just seems to me the same as using `python3` from a technical perspective, unless only cinnamon can change it. In the end even if something like that is implemented it's not going to fix any of the previous versions. 

Anyway, I'm ok with this change, although I'm sure [it will break someone's setup](https://imgs.xkcd.com/comics/workflow.png)

**Comment by Drugwash2** [comment]
> That just seems to me the same as using `python3` from a technical perspective

From a certain point of view it's true, but as it is now any change of path sometimes requires multiple changes in multiple files; having only one declaration would just simplify any further changes.
Not sure what to say regarding previous versions.
As for setups and workflows... well, the current situation already broke someone's workflow as seen in #4331, reason why this change has been suggested.

**Comment by mchilli** [comment]
Seems ok for me, anyway the path `/usr/bin/python` doesn't seems to exist anymore since Mint 20, but 
 I think that only applies for `softyubikey@yubiserver.include.gr`, which seems not to be under active development.

**Comment by Siphalor** [comment]
> Seems ok for me, anyway the path `/usr/bin/python` doesn't seems to exist anymore since Mint 20, but I think that only applies for `softyubikey@yubiserver.include.gr`, which seems not to be under active development.

Ah, nice spot.
Not sure if I should change that to `/usr/bin/python2`, since that might actually result in a change of behavior then, since there is `python-is-python2` and `python-is-python3` nowadays ^^
They probably need to address that anyway if it's still under development.

**Comment by Siphalor** [comment]
Since this has pr has been lying around for a few months now, I'd like to give this a little bump and ask if there's anything that still needs to be done to get this merged.

Sorry for notifying everyone in this thread, but I want to prevent this going completely stale :)

**Comment by brownsr** [comment]
I was never convinced, so I just let it run to gather comments.  Still in that position.

Regards

Simon

**Comment by claudiux** [comment]
In any case, this PR is too old to be merged and concerns too many different applets. Let's leave it to their respective authors to make the changes they deem necessary. Ping @mchilli @joka42 @icarter09 @jake1164 @lauritsriple @gfreeau @jonath92 @jerrywham @cardsurf @Gr3q.

**Pull request closed without merging**
