### PR TITLE
vpnLookOut@claudiux applet: Vpn look out2

### PR DESCRIPTION
**Pull request by claudiux**
Hi,

This is the version 2.0.0 of the vpnLookOut Applet, with new features, some bugs fixed, and a integrated tool to help the user to install dependencies, if any.

Translations in French, Spanish, Italian are available.

Can you pull this version into your master branch of cinnamon-spices-applets, please?

I wish you a very happy new year!

Bests regards.

Claudiux

### CODE REVIEW

**Comment by claudiux** [comment]
Many thanks @jaszhix ! Happy New Year !

**Comment by claudiux** [comment]
Why is the screenshot.png image in https://cinnamon-spices.linuxmint.com/applets/view/305 still the same? Can you update it with the new one, please, if it's possible ? It displays a screen shot in English (it was a request from NikoKrause), including last features. Thanks.

**Comment by jaszhix** [comment]
There is currently a delay for when the image cache gets updated. It will eventually be updated in a day or so. The design team is aware of the problem.

**Comment by claudiux** [comment]
Ok. I will wait for the goodwill of the cache. ;)

**Pull request merged**
