### PR TITLE
temperature@fevimu: ru_RU po

### PR DESCRIPTION
**Pull request by Ilis**
New Russian translation for temperature@fevimu

### CODE REVIEW

**Comment by NikoKrause** [comment]
Please use the more proper ID `ru.po` instead of `ru_RU.po`

**Comment by Ilis** [comment]
I'm newbie in git and po editing :)

Please, let me know, should I change file name, or change Language code inside the file, or both? Should I do new commit or pull request?

**Comment by NikoKrause** [comment]
Rename the file to ru.po and change the Language code in the file itself with a normal editor to:
```
"Language: ru\n"
```

For the future, if you create a new translation, poedit asks for the target language. Just select "Russian" instead of "Russian (Russian Federation)".

You can add a new commit in this branch. The new commit will appear in this PR automagically

**Comment by Ilis** [comment]
Well, I did new commit. Is «automagically» happens?

**Pull request merged**
