### PR TITLE
mylauncher@markbokil.com: Fix issue where updating the applet will remove custom menu config

### PR DESCRIPTION
**Pull request by Centurix**
When updating the mylauncher@markbokil.com, it will overwrite any custom menu settings. This is due to the configuration file being present in the applets code directory. This change uses the applets files as a default configuration and copies the contents to the .config sub directory in the users home. This means that the configuration will survive applet updates in the future.

Fixed a hardcoded username in the default configuration for the home directory to the tilde shortcut

Fixed command line library references from Main.Util to Util.

@mbokil

### CODE REVIEW

**Review by rcalixte — APPROVED** [review]

**Comment by rcalixte** [comment]
Thank you @Centurix! This is currently unmaintained. If you are interested in taking over as the maintainer, just say the word.

**Comment by robouden** [comment]
Please fix it... I normally save my config before updating..

**Comment by Centurix** [comment]
> Thank you @Centurix! This is currently unmaintained. If you are interested in taking over as the maintainer, just say the word.

Thanks, sure thing, I use this applet a lot so I'm more than happy to take over the maintenance.

**Comment by Centurix** [comment]
> Please fix it... I normally save my config before updating..

This should start appearing in the software updates. This update will move the settings to a different config area so make sure you backup your settings again. And then that should be the last time you'll have to do it as subsequent updates won't overwrite the config area.

**Comment by robouden** [comment]
Chris,

Thanks!!! Always wanted this to be fixed.
Just updated and it works!!

Regards
Rob

**Pull request merged**
