### PR TITLE
weather@mockturtl Update 2.3.0

### PR DESCRIPTION
**Pull request by Gr3q**
Changes:
* Fixed Issues with Debian, now Polyfilling Promises when needed
* Reworked on how to import from other files, now in line with other applets
* Utility functions moved to other file.
* Typescript declarations reorganised now they make a little bit more sense _(generated declarations from gir files still don't work that well, although mostly working)_
* Can now build from same source down to Cinnamon Version 3.0
* Fixed some styling issues with some themes (Adapta, etc) where the Forecast box did not have enough padding
* Sunset/Sunrise and Day names are using the system locale _(3.4+)_

Issues:
* Error messages are not working properly, due to how the applet is refreshed _(and also due to the backwards style of directly accessing the applet from the providers to display errors)_
* Promise polyfill is always used _(some weird issue that Promise becomes undefined if a ```var Promise = promisePoly.Promise as PromiseConstructor;``` line exists, even if it has not ran yet. no line, Promise works)_

Tested on:
Cinnamon 3.0, 3.2, 3.4, 3.6, 4.2

Have a look through and use it for a couple of days to check if it's alright.

I'll try to rework the Error Messages on the time being.

### CODE REVIEW

**Comment by brownsr** [comment]
Seems to work OK, though as I'm not a regular user of this applet there may be things there that others can see.  I found the way it only used the co-ordinates and not the code a bit confusing, but that looks as if it was there previously.  I'm not sure from your PR message whether you want this merged now, or you are still working on this.  Could you clarify ?

**Comment by Gr3q** [comment]
Don't merge it now, I created the PR to get some feedback, find out if there are issues etc.

I want to make sure the applet does not have regressions, like the one you found.

**Comment by brownsr** [comment]
what are the plans ?  Are you planning to make further changes in the near future or do you want me to close this for now, so you can reopen when you are ready, or shall I just leave it like this for a few more weeks ?

**Comment by Gr3q** [comment]
Sorry, I was on holiday. Please leave it open, I will finish everything up around the PR by the end of this week, then it will be ready for merge.

**Comment by brownsr** [comment]
Thanks for the update. I hope you enjoyed the holiday. No rush, take all
the time you need, now I know why things went silent! 😀

**Comment by Gr3q** [comment]
I consider the PR ready.
I will use the final version today on my computer just to make sure everything works alright.

You can merge it tomorrow.

**Pull request merged**
