### PR TITLE
Cinnamenu@json: add l10n template, translation updates

### PR DESCRIPTION
**Pull request by NikoKrause**
* update translations against template
* complete German translation

@jaszhix

### CODE REVIEW

**Comment by jaszhix** [comment]
This looks great, thanks for helping with the translation. 

Feel free to merge.

**Comment by Odyseus** [comment]
Hello, everybody.

@NikoKrause: A little observation. You don't need to call **Gettext.bindtextdomain** on all files. With just calling it once in the first js file that is loaded is enough. In the case of this applet, I guess that would be the applet.js file.

**Comment by NikoKrause** [comment]
@Odyseus 
Better?

**Comment by Odyseus** [comment]
@NikoKrause 👍

**Pull request merged**
