### PR TITLE
azan@fahri.nurul.id: Change author field to Github username

### PR DESCRIPTION
**Pull request by jaszhix**
@fahrinh

### CODE REVIEW

**Comment by fahrinh** [comment]
@jaszhix sorry, i didn't realize that :(

btw, is that a reason why this applet is not appeared on `Applets` > `Available applets (online)` ?

**Comment by NikoKrause** [comment]
It should be listed there. Did you refreshed the list?

**Comment by fahrinh** [comment]
Yes, I have refreshed the list
screen shot 2017-11-30 at 8 43 29 am

**Comment by NikoKrause** [comment]
It's here:
screenshot-window-2017-11-30-094443

How does Sort by Date look like?

**Comment by fahrinh** [comment]
Nope.
Even after `.cinnamon` is deleted
```
rm -rf ~/.cinnamon
```
screen shot 2017-11-30 at 10 31 37 pm

I think it is related with issues [#6567](https://github.com/linuxmint/Cinnamon/issues/6567) and [#2215](https://github.com/linuxmint/Cinnamon/issues/2215)

I experienced the same symptomps before. Failed to access the server then many error boxes popped up.

And, now, connecting to the server (and downloading data) is not a problem but my applet is still not appeared

**Comment by fahrinh** [comment]
Are there any cache directories I can delete?

**Pull request merged**
