### PR TITLE
Added wakapidisplay@babico

### PR DESCRIPTION
**Pull request by babico**
Wakapi is selfhosted WakaTime. So they have same API template. Instead of create new one I just fork Wakatime applet from #4666 @inventor96

### CODE REVIEW

**Comment by inventor96** [comment]
There's some upgrades being done over in #4849 that you'll probably want to include here.

**Comment by babico** [comment]
> There's some upgrades being done over in #4849 that you'll probably want to include here.

Thanks I added @Gr3q's HttpLib module found in other applets. Probably my implementation is not good enough because I am not good with JS thanks for the feedback and original wakatime applet @inventor96.

**Comment by claudiux** [comment]
Just adding this applet on a panel, these messages appear in `~/.xsession-errors`:
```
Gjs-Message: 14:06:49.626: JS LOG: [LookingGlass/info] Installing settings for wakapidisplay@babico
Gjs-Message: 14:06:49.626: JS LOG: [LookingGlass/info] Settings successfully installed for wakapidisplay@babico
Gjs-Message: 14:06:49.637: JS LOG: [LookingGlass/info] Loaded applet wakapidisplay@babico in 674 ms

(cinnamon:2297): Gjs-WARNING **: 14:06:49.997: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:


(cinnamon:2297): Gjs-WARNING **: 14:11:50.565: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
```

I don't yet have a wakapi server or account.

**Comment by babico** [comment]
> Just adding this applet on a panel, these messages appear in `~/.xsession-errors`:
> 
> ```
> Gjs-Message: 14:06:49.626: JS LOG: [LookingGlass/info] Installing settings for wakapidisplay@babico
> Gjs-Message: 14:06:49.626: JS LOG: [LookingGlass/info] Settings successfully installed for wakapidisplay@babico
> Gjs-Message: 14:06:49.637: JS LOG: [LookingGlass/info] Loaded applet wakapidisplay@babico in 674 ms
> 
> (cinnamon:2297): Gjs-WARNING **: 14:06:49.997: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
> 
> 
> (cinnamon:2297): Gjs-WARNING **: 14:11:50.565: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
> ```
> 
> I don't yet have a wakapi server or account.

https://wakapi.babico.name.tr you can use mine instance for testing. I try to fix warning with my poor JS knowledge.

**Comment by claudiux** [comment]
Thank you.

**Comment by claudiux** [comment]
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises

**Comment by claudiux** [comment]
Latest version tested. Please avoid flooding `~/.xsession-errors` with this kind of messages, while settings url and api key are not set:
```

Gjs-Message: 15:14:51.244: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:06.762: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:44.268: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:44.746: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:44.751: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:44.784: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:44.836: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:44.865: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:44.900: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:44.926: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:44.957: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:44.961: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:44.986: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:44.992: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.019: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.047: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.079: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.110: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.140: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.170: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.201: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.227: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.259: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.290: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.318: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.348: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.383: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
Gjs-Message: 15:15:45.410: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
```

**Comment by babico** [comment]
> Latest version tested. Please avoid flooding `~/.xsession-errors` with this kind of messages, while settings url and api key are not set:
> 
> ```
> 
> Gjs-Message: 15:14:51.244: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:06.762: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:44.268: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:44.746: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:44.751: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:44.784: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:44.836: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:44.865: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:44.900: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:44.926: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:44.957: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:44.961: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:44.986: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:44.992: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.019: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.047: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.079: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.110: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.140: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.170: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.201: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.227: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.259: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.290: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.318: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.348: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.383: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> Gjs-Message: 15:15:45.410: JS LOG: [LookingGlass/error] [wakapidisplay@babico/applet.js:91] TypeError: data is null
> ```

I think I fix the problem

**Pull request merged**
