### PR TITLE
stopwatch@pcurtis.com Revert change that removed changelog.txt from applet folder

### PR DESCRIPTION
**Pull request by pdcurtis**
The changelog.txt file was removed from the applet folder in error in a mass pull request. #148

It is accessible from withing the applet from the right click (context) menu by the user along with a copy of the README.md file which is used as help file.

In my view changes to multiple applets are inadvisable, especially without consultation with an active author and can have unintended consequences as in this case and for 4 other applets. In fact the overall README.md on this repository states:

Pull requests from other people
- in addition to the checks specified above, if the pull requests comes from somebody else than the author, the reviewer will need to check the nature of the changes.
- If the changes represent a bug fix, the PR can be merged.
- **If the changes represent a change in functionality, or in look and feel, or if their implementation could be questioned and/or discussed, the reviewer should leave the PR open and ask the author to review it.**
 - **If the author is happy with the PR, it can then be merged. If he's not, it can be closed instead**.

### CODE REVIEW

**Comment by brownsr** [comment]
This PR is showing that no files have been changed.  Still want it merged ?

**Comment by NikoKrause** [comment]
@pdcurtis 
As brownsr said. Your PR didn't changed anything. I created a PR, which undo the changes I made.
Sorry again for breaking your applet. Won't happen again.

I moved the changelog files back. You need to approve or decline my PR.
The README file in your applets is now doubled. We can try to create a symbolic link.
I mean leave `UUID/files/UUID/README.md` as it is and create a symbolic link `UUID/README.md`.
This way you don't have to edit both files each time. 
It would be an experiment though, because I don't know, if the spices website handles the symbolic link. It's up to you. If you want me to test it for you let me know.

Hope everything is ok now.

**Comment by pdcurtis** [comment]
@brownsr There is no point in merging the request as my PL must have been generated at the same time that @NikoKrause was also fixing the same problem, quite a coincidence after several weeks!

@NikoKrause Thanks for fixing the problem on all the applets.

@ anyone. I notice that every one of my fetch and merges of upstream are showing up individually in the merge request. Is this a problem and is there a way of avoiding all this 'noise' whilst keeping everything up-to-date in my repositories? Is it worth producing some basic notes for those of us who are not full time users of Git and Github on the preferred way of using this repository?

**Comment by Odyseus** [comment]
Hello, everybody.

@pdcurtis: I compiled in my repository's wiki some basic GitHub tasks. The section called [Contribute to someone's repository](https://github.com/Odyseus/CinnamonTools/wiki/GitHub-tips-&-tricks#contribute-to-someones-repository---source) is the method that I use to create pull requests for third party repositories. The section called [Working with big repositories](https://github.com/Odyseus/CinnamonTools/wiki/GitHub-tips-&-tricks#working-with-big-repositories---source) might also be of interest to you. It will allow you to check out just the parts of a repository that you want to work with and nothing else.

**Comment by brownsr** [comment]
@pdcurtis   Don't worry too much about the effects of keeping up to date that you describe.  They can be avoided by rebasing, but also anyone able to commit to the repository in github has access to squash/merge facilities in addition to the standard merge.   That means a string of commits can be squashed down into just one commit when merging.

**Comment by pdcurtis** [comment]
@Odyseus Thanks for sharing your documentation and to @brownsr for his information.
Some of the information I already knew  but some of the ideas were knew and I will investigate and there were some additional insights on other areas.

I have also put together some documentation which I am happy to share but one should note it was mostly written before the changes to applet handling and is currently very egocentric as it was written for people starting to write applets and use use git to keep them under version control and for those who might want to contribute to my applets. It is at www.pcurtis.com/git.htm . Any comments or corrections are welcome.

@NikoKrause has also written a  a quick tutorial on How to add l10n/translation support to an applet at NikoKrause/CinnVIIStarkMenu#19 which may help fill in another missing area of documentation.

@ everyone: Where should discussions such as this and documentation be held - a closed PR is obviously not the ideal place! I have raised the problems of documentation several times before as the little that exists for applets is scattered and much is for earlier versions of Cinnamon with a few occasional words of wisdom in Segfault updating things and now the README.md for the spices repositories. I fear we are setting a barrier which is impossibly high for any new contributors and even existing authors.

**Comment by JosephMcc** [comment]
In most cases the best place for Cinnamon documentation is here: https://github.com/linuxmint/Cinnamon/tree/master/docs/reference in Cinnamon itself. This is generally more up-to-date and can be viewed with Devhelp as long as you have the cinnamon-doc package installed. It probably would be a good idea to provide some docs here for working with, and submitting to, this repo.

In general your commits should not have all of those merge commits of upstream/master in them. If you want to pull upstream changes into a branch you are working on you should first update your master branch. `git checkout master` followed by `git fetch upstream` and `git merge upstream/master`.

Once you do that you can checkout your working branch branch and run `git rebase master`. That will cleanly add all of the upstream changes to your working branch without all the merge commmits.

Whenever you want to start working on a new branch you should first fetch and merge upstream master as described above before creating the branch.

**Comment by NikoKrause** [comment]
https://github.com/NikoKrause/CinnVIIStarkMenu/issues/28

**Comment by pdcurtis** [comment]
@NikoKrause Another nice tutorial. I am glad you show the mechanisms to ensure that the author is alerted to the PL and given the chance to comment. 

Is it however better to tidy up the Branch after the Pull Request has been successfully merged and closed rather than keep every update in a separate branch by deleting it on the local copy and on origin? This can be done by:

```
git push origin --delete <branch_name>
git branch -D <branch_name>
```

Note1:  the forced delete is deliberate as it means that one does not need to merge the branch before deleting as it will eventually appear via the Pull Request from origin to upstream and then the pull from upstream to master.
Note 2; For completeness I believe that when you are working on several machines you may need to purge the stale branch  on the other machines by something like `git fetch --all --prune` on each machine

This keeps your local master and upstream master looking more like upstream and it should have all your commits made to the branch in it via the successful PL including changes made during the merge cycle such as squashing which @brownsr indicated could take place.

**Comment by pdcurtis** [comment]
@JosephMcc Thanks for the information on cinnamon documentation - I had not found that before and I have now installed cinnamon-doc and devhelp and the applet settings information is much more up-to-date on 3.2 than I had previously. 

Some of the documentation and tutorials however need to be readily available especially if we expect to get any new authors - we are making it very difficult to get started. I would never have started if the situation had been like this a few years ago, even building on an existing applet as I did. I only started to use git when I had several applets and felt a formal version control was becoming essential and it was (and still is) a steep learning curve to climb.

I will explore the use of `git rebase` which I have largely ignored up till now, as a good way to clean up the branch prior to the PR.

**Pull request closed without merging**
