### PR TITLE
Add translation for Show or record desktop

### PR DESCRIPTION
**Pull request by giwhub**
@cranes-bill

### CODE REVIEW

**Comment by cranes-bill** [comment]
Thanks, but i would like if somebody could help me fix the English string first. I'm afraid due to my bad English, they are not completely correct. That is the reason why i commented the _gettext support_.

**Comment by NikoKrause** [comment]
Looks mostly good to me.
@giwhub
Can you check?

**Comment by giwhub** [comment]
It looks good but yet has some careless mistakes,I can help if you wish.

**Comment by cranes-bill** [comment]
> It looks good but yet has some careless mistakes,I can help if you wish.


Yes, please!

Also, did you try the applet with translation support enabled, and does it works for you?
I'm asking, because if i enable the _translation code_, the applet fails to load to me. I found the reason is in _predefined message strings_. I mean:
`const LOCKMESSAGE = _("String for translation") + "\n";`
When i write those messages directly into the function, everything work fine. So if that also does not works for you, it must be changed. 

P.S.: Sorry for the bad English!

**Comment by giwhub** [comment]
screenshot-window-2017-04-28-220606

I retry it,it does work for me.

**Comment by cranes-bill** [comment]
That's a good news. So please correct the strings where you things it's necessary, then can merge it!
Thank you very much!

**Comment by NikoKrause** [comment]
@cranes-bill
You try to translate a const here. Changing the value after it's init is not possible. So I'm not sure what happens, if it gets translated.

@cobinja says:
> My assumption would be that it always uses the initial value returned by _(). If the language changes afterwards, I'd say it either keeps the original value or crashes horribly

**Comment by cranes-bill** [comment]
OK, i will change it.

**Pull request closed without merging**
