### PR TITLE
 qredshift@quintao: Add locale support

### PR DESCRIPTION
**Pull request by kelebek333**
Add locale support
Add pot file
Add tr.po file

@raphaelquintao

### CODE REVIEW

**Comment by claudiux** [comment]
Hi @kelebek333,
`Reload Applet` should be translatable.
https://github.com/linuxmint/cinnamon-spices-applets/blob/d5b7b3a6ef06bbd568d139e32cf64c0787c1140c/qredshift%40quintao/files/qredshift%40quintao/applet.js#L114
https://github.com/linuxmint/cinnamon-spices-applets/blob/d5b7b3a6ef06bbd568d139e32cf64c0787c1140c/qredshift%40quintao/files/qredshift%40quintao/applet.js#L154

**Comment by kelebek333** [comment]
Hi @claudiux ,

I added other missing translations. You can update locale file.

Best regards

**Comment by claudiux** [comment]
Thank you, @kelebek333.

**Comment by brownsr** [comment]
ping @raphaelquintao

**Comment by raphaelquintao** [comment]
Hi everyone!
That sounds very good to me.
I will test when I can.
By me can be accepted.

Happy new year guys!

**Pull request merged**
