### PR TITLE
betterlock: added russian translation

### PR DESCRIPTION
**Pull request by NikoKrause**
@entelechy are you okay with this change?

### CODE REVIEW

**Comment by NikoKrause** [comment]
@andreevlex
Are you the author of this applet (are you entelechy)?

**Comment by andreevlex** [comment]
no, for You this fact is important?

**Comment by NikoKrause** [comment]
I'm confused. The author is supposed to approve the changes.

**Comment by andreevlex** [comment]
I apologize for the intrusion. I wanted to help in checking the translation, as itself from Russia

**Comment by NikoKrause** [comment]
Ah. Okay. Thanks.

**Comment by collinss** [comment]
This applet hasn't had any activity from the author since 2012. I'm going to assume it's abandoned and merge this and any other PR's that are opened on this applet.

**Pull request merged**
