### PR TITLE
multicore-sys-monitor@ccadeptic23: Fix applet geometry bugs.

### PR DESCRIPTION
**Pull request by evg-zhabotinsky**
Fixed applet graphics being slightly off-center and clipped.
(Width and height were off by a few pixels.)

Fixed incorrect vertical scaling in HiDPI.
(`panel_height` is already scaled and scaling factor was applied once more to it, leaving half the applet off-screen at 2x scale)

@jaszhix

### CODE REVIEW

**Comment by jaszhix** [comment]
Part of my attempt at high DPI support was trying to get the labels to scale as well, but apparently that scaled the entire applet incorrectly. Current version:
image

PR:
image

Not sure what the solid lines at the bottom of the network and disk graphs are from, probably was always there, but hidden from the applet being positioned too far down.

Anyway, it looks good, definitely more usable for high DPI users. I don't have a high DPI display, so Cinnamon is hard to use for very long with it on. Thanks for taking time to fix this!

**Comment by evg-zhabotinsky** [comment]
That was fast. Too fast, in fact.
I don't use labels so I forgot about them. Fix is the same as with the pie chart: don't divide size by scale as its already a function of height.
I guess I have to open another PR.

**Comment by jaszhix** [comment]
I went ahead and merged it because it was a usability issue... the github integration adds the `In Progress` tag to every PR, I recommend adding "WIP" to the title.

**Comment by evg-zhabotinsky** [comment]
It was not intended as a WIP. Just saying that after finding a less important bug introduced by a fix for more important bug it might still be worthwhile to wait for a reply, that's all.

**Pull request merged**
