### PR TITLE
Landing more Hungarian translations :smile: 

### PR DESCRIPTION
**Pull request by KAMI911**

### CODE REVIEW

**Comment by NikoKrause** [comment]
Thx for your translations. There's an error in one of your translation files:
```
[SpicesUpdate@claudiux] The following errors were found in translation file 'hu.po':
files/SpicesUpdate@claudiux/po/hu.po:7: invalid nplurals value
                                        Try using the following, valid for Hungarian:
                                        "Plural-Forms: nplurals=2; plural=(n != 1);\n"
files/SpicesUpdate@claudiux/po/hu.po:7: invalid plural expression
                                        Try using the following, valid for Hungarian:
                                        "Plural-Forms: nplurals=2; plural=(n != 1);\n"
msgfmt: found 2 fatal errors
HINT: Most errors in translation file `hu.po` can usually be prevented and solved by using Poedit.
```

**Comment by NikoKrause** [comment]
https://github.com/KAMI911/cinnamon-spices-applets/pull/1

**Comment by KAMI911** [comment]
Hey @NikoKrause!
Fix is committed! I hope this will make things better.

**Comment by NikoKrause** [comment]
Thanks. Everything good now.

**Pull request merged**
