### PR TITLE
Updated Hungarian translation

### PR DESCRIPTION
**Pull request by KAMI911**

### CODE REVIEW

**Comment by fredcw** [comment]
@claudiux Woohoo, you've got merge permissions? This is great. Is it just applets or other repos as well?

**Comment by claudiux** [comment]
@fredcw https://github.com/orgs/linuxmint/people

**Comment by fredcw** [comment]
@claudiux I don't understand, your name isn't on that page?

**Comment by claudiux** [comment]
@fredcw Reload the page, it's now public.

**Pull request merged**
