### PR TITLE
[Radio3.0@claudiux] v1.2.1 - Now compatible with openSUSE. Add new shortkeys.

### PR DESCRIPTION
**Pull request by claudiux**
Hi @brownsr 

checkDependencies.js is now able to install all dependencies on openSUSE.

Can you merge this branch with your master one, please?

Kind regards.
Claudiux

### CODE REVIEW

**Comment by claudiux** [comment]
I don't understand why the Chinese translation of another applet prevents to validate this spice.

**Comment by Slinet6056** [comment]
It seems that both #4775 and #4777 modified `zh_CN.po`, causing problems after merging.

**Comment by Slinet6056** [comment]
Maybe try changing the `zh_CH.po` to #4777 would work.

**Comment by claudiux** [comment]
Thank you @Slinet6056. This was solved using #4777.

**Comment by claudiux** [comment]
@brownsr 
I can drop https://github.com/linuxmint/cinnamon-spices-applets/pull/4784/commits/ddc9ee85fc39747a00b10fb017831d7de1e1dbe9 once #4791 is merged, if you wish.

**Comment by claudiux** [comment]
@brownsr This PR is now ready to merge.

**Comment by claudiux** [comment]
@brownsr Can you merge this PR, please?

**Pull request merged**
