### PR TITLE
10 Applets by Odyseus removal

### PR DESCRIPTION
**Pull request by Odyseus**

### CODE REVIEW

**Comment by NikoKrause** [comment]
Hey, can I ask why you remove all your applets?
Just want to know the reasons for myself. I'm curious.

**Comment by Odyseus** [comment]
Hello, @NikoKrause.

You can ask, but a prefer not to answer. Suffice to say, I want all my xlets gone from the Spices website.

**Comment by NikoKrause** [comment]
screenshot-area-2017-08-18-162515

**Comment by Eik-S** [comment]
I miss the multi-translator :sob:

**Comment by Ilis** [comment]
So sad.

**Comment by mfreeman72** [comment]
This is upsetting. I didn't realize you had done this until your Cinnamon Tweaks extension that I loved didn't work in Cinnamon 3.6. I went to find the page on Spices and Github, and they were gone. Now Cinnamon is much less fun to use. I wish you would either reconsider and re-release these, or at the very least offer the code to someone else so these things can continue to be used. I don't know what happened to make you remove them, and I don't need to know. But this is really frustrating and sad.

**Comment by Corto-landese** [comment]
I liked a lot your applets (custom cinnamon menu [which was VERY customized on my desktop], simple to do list and others) and I am very sad that you remove them.

**Comment by NikoKrause** [comment]
For those of you, who missed the Cinnamon Tools from @Odyseus. 
If you are willing to install them manually, you can download his applets/extensions on his CinnamonTools repo on GitHub.

**Comment by Corto-landese** [comment]
Thank for your answer and this solution.

 

I don't know how to install directly an app but, because I like a lot your product, I will learn how to to  ;-)

 

regards

 

(and if I succeed I will send you a screenshot of the wonderful result with nice icons and smart parameters.  :-)   )

 

 

 

 

 

> Message du 28/06/18 12:18
> De : "NikoKrause" 
> A : "linuxmint/cinnamon-spices-applets" 
> Copie à : "Corto-landese" , "Comment" 
> Objet : Re: [linuxmint/cinnamon-spices-applets] 10 Applets by Odyseus removal (#1169)
> 
>
> For those of you, who missed the Cinnamon Tools from @Odyseus.
> If you are willing to install them manually, you can download his applets/extensions on his CinnamonTools repo on GitHub.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linuxmint/cinnamon-spices-applets","title":"linuxmint/cinnamon-spices-applets","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/linuxmint/cinnamon-spices-applets"}},"updates":{"snippets":[{"icon":"PERSON","message":"@NikoKrause in #1169: For those of you, who missed the Cinnamon Tools from @Odyseus. \r\nIf you are willing to install them manually, you can download his applets/extensions on his CinnamonTools repo on GitHub."}],"action":{"name":"View Pull Request","url":"https://github.com/linuxmint/cinnamon-spices-applets/pull/1169#issuecomment-400987133"}}}[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/linuxmint/cinnamon-spices-applets/pull/1169#issuecomment-400987133", "url": "https://github.com/linuxmint/cinnamon-spices-applets/pull/1169#issuecomment-400987133", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [linuxmint/cinnamon-spices-applets] 10 Applets by Odyseus removal (#1169)", "sections": [ { "text": "", "activityTitle": "**NikoKrause**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@NikoKrause", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "java-script", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"linuxmint/cinnamon-spices-applets\",\n\"issueId\": 1169,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "targets": [ { "os": "default", "uri": "https://github.com/linuxmint/cinnamon-spices-applets/pull/1169#issuecomment-400987133" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 250465925\n}" } ], "themeColor": "26292E" } ]

**Pull request merged**
