### PR TITLE
placesCenter@scollins: applet.js - Scrollview added to the user secti…

### PR DESCRIPTION
**Pull request by claudiux**
…on and the system section.

Hi,

I make a contribution to the applet placesCenter@scollins, respecting the code of the author @collinss. I added a scrollview to the user section and the system section so that this applet can display the complete list of its favorite places or mounted volumes, even if it's very large.

Is it possible to merge my placesCenter branch with your master branch, please ?

Best regards,

Claudiux

### CODE REVIEW

**Comment by claudiux** [comment]
Hi @collinss,

Is there a problem with this code? Should I change something?

**Comment by collinss** [comment]
Sorry, @claudiux. I was just thinking last night before I went to bed that I needed to get to this. I've been really busy lately, and haven't had a chance to review and test this yet. What little time (and brainpower) I've had for coding, I've spent fixing up a couple of pr's I had on Cinnamon. This week should be a little bit lighter, though, so I'll try to get to it in the next couple of days.

**Comment by claudiux** [comment]
Don't worry, @collinss, it was just a question. No hurry, take all the time you need.

**Comment by claudiux** [comment]
Hi @collinss, would you have time to review and test these 21 lines of code, please? That would be great!

**Comment by collinss** [comment]
Sorry man, I haven't really had a day off in at least a month. I will have one on Saturday though. I'll try to get to it then. If it were with something simple I could just look it over and that would be enough, but things are never simple when clutter is involved so I'd prefer to test it first. (From personal experience I can tell you that clutter stuff doesn't always work the way you expect - especially when it comes to layout.)

**Comment by claudiux** [comment]
It's great, man. Thank you.

On my computers, it works like a charm since one month, with no error message in .xsession-errors and glass.log.

**Comment by collinss** [comment]
Sorry it took so long to get to this. It looks good though. Thanks!

**Comment by claudiux** [comment]
Thanks to you !

**Pull request merged**
