### PR TITLE
[radio@driglu4it] update types

### PR DESCRIPTION
**Pull request by jonath92**
just a small update to apply the new types

### CODE REVIEW

**Review by Gr3q — CHANGES_REQUESTED** [review]
Let me update the declarations for you, `notify` callback expecting a number return value is a mistake in the generated code.

**Comment by jonath92** [comment]
> Let me update the declarations for you, `notify` callback expecting a number return value is a mistake in the generated code.

Ok thank you :-)

**Comment by jonath92** [comment]
There is also another problem in this pr. The popup menu doesn't open anymore when clicking on stop.  I need to investigate. So right now this definitely shouldn't be merged

**Comment by Gr3q** [comment]
If you return `true` in callbacks which are expecting it I think that means the event has been handled, no need to pass it up the chain.

Previously you didn't return anything (well, undefined), which was interpreted as `false`. If you return false I think you will be fine.

**Comment by jonath92** [comment]
> Previously you didn't return anything (well, undefined), which was interpreted as false. If you return false I think you will be fine.

yes, thanks. That fixed it

**Comment by jonath92** [comment]
@brownsr from my point of view, it can now be merged :-).

**Pull request merged**
