### PR TITLE
system-controls@rcalixte: Initial release

### PR DESCRIPTION
**Pull request by rcalixte**
system-controls@rcalixte: Initial release of 'system-controls@rcalixte' applet

Add new minimal applet for system controls

### CODE REVIEW

**Comment by brownsr** [comment]
is the gnome-session command intended ?

**Comment by rcalixte** [comment]
> is the gnome-session command intended ?

It was... but I now realize it was incorrect. 😅 Let me fix it quickly.

**Comment by rcalixte** [comment]
Updated! Thanks for the review!

**Comment by rcalixte** [comment]
@brownsr Updated! Thanks for the review!

**Pull request merged**
