### PR TITLE
Add function: You can specify sound volume.

### PR DESCRIPTION
**Pull request by kancolle386**
applet.js
Add a parameter to spawnCommandLine.

settings-schema.json
Add scale for specify volume.

### CODE REVIEW

**Comment by brownsr** [comment]
ping @jake1164

**Comment by NikoKrause** [comment]
The last contributions from @jake1164 on his applets seem to be more than 2 years ago. Also I can't remember seeing any reactions to pull requests or issues regarding his applets.

So I suggest that we give it another 10 days and if we don't get any reaction we can call his applets abandoned.

@kancolle386 would you be interested to be the new maintainer in this case? If not, we just set the author to none.

**Comment by kancolle386** [comment]
What happens to this applet when author is set to none?

**Comment by brownsr** [comment]
We won't refer any changes to the author, as there is none. So changes in functionality can be made freely by anyone.

Regards

Simon

**Comment by brownsr** [comment]
It's been a while now.  I'm going to assume applet is abandoned and merge this.

Regards

Simon

**Comment by kancolle386** [comment]
Hello, I would try maintainer of this applet.

**Pull request merged**
