### PR TITLE
Update applet.js

### PR DESCRIPTION
**Pull request by pimisen**
Added blank/space in Line 807 before capitalizeFirstLetter(_(mainCondition));
This improves the visual impression in the Systray.

### CODE REVIEW

**Comment by pimisen** [comment]
Added blank/space in Line 807 before capitalizeFirstLetter(_(mainCondition));
This improves the visual impression in the Systray.

**Comment by brownsr** [comment]
Could you do a before and after screenshot ?  I'm a little puzzled by this as the spacing I am seeing looks appropriate, so perhaps I am missing something.

Regards

Simon

**Comment by Gr3q** [comment]
If you want, you can just insert a space here if it does not look good for you:
image

I suspect your theme is styling differently

**Comment by pimisen** [comment]
@brownsr Please find a before / after screenshot attached. I am using windows 10 theme (Windows-10-Dark-3.2-dark
after
before
@Gr3q Thanks for the hint, this will keep me from changing in the sources after every update :-)
)

**Comment by brownsr** [comment]
I've decided not to pull this change.  It looks to be theme related, and there's the hint from Gr3q that you can use to adjust things.  Sorry, hope you will understand, this would cause regressions in other themes.

Regards

Simon

**Comment by pimisen** [comment]
Hello @brownsr 
WHAT? Are you kidding me? ;-) 
No, serious: No need to sorry, this is clearly a theme issue, i should have cancelled this pull request on my own.
I do not only understand taht, i would have also not pulled it :-) Thanks for letting me be part of the open source community and being so nice to me.
Best
Michael

**Comment by brownsr** [comment]
Michael

If you are getting into the groove with changes, there's always plenty to fix out there ;-)

Regards

Simon

**Pull request closed without merging**
