### PR TITLE
scripts@paucapo.com: Fix screenshot.png link

### PR DESCRIPTION
**Pull request by muzena**

### CODE REVIEW

**Comment by muzena** [comment]
@NikoKrause 
Why screenshot isn't visible?
https://cinnamon-spices.linuxmint.com/applets/view/185

**Comment by NikoKrause** [comment]
Do you mean the screenshot in the README or the other?

For the screenshot in the README I'm not sure, but I would try to remove the tooltip, i.e.
```
![Script menu and configure dialog](https://github.com/linuxmint/cinnamon-spices-applets/raw/master/scripts%40paucapo.com/screenshot.png)
```

For the other. It's a problem with the cache of the website. This issue is known and will be tackled later. For now clefebvre has to clean the cache manually once in a while.

**Comment by muzena** [comment]
@NikoKrause 
What about translation, can I commit po's for multiple applet in one PR or po's for each applet in separate PR?

**Comment by NikoKrause** [comment]
Hmmm... I think if it's only the .po files it's okay, if you add them in one PR.

**Pull request merged**
