### PR TITLE
cryptocoin@guantanamoe: Price alerts

### PR DESCRIPTION
**Pull request by bkmeneguello**
Added price alerts
@philtyl @jaszhix

### CODE REVIEW

**Comment by brownsr** [comment]
@philtyl  OK with you ?

**Comment by philtyl** [comment]
Approved

**Comment by brownsr** [comment]
@bkmeneguello All tested ?  I have no way to do that myself to check it works fine.

**Comment by bkmeneguello** [comment]
I'm using for a few months. All bugs fixed. And default config (with no alerts) does nothing.

**Pull request merged**
