### PR TITLE
sysmonitor@orcus: Fix for Cinnamon 3.8

### PR DESCRIPTION
**Pull request by jaszhix**
@OrcusCZ

### CODE REVIEW

**Comment by cevadoztug** [comment]
This applet is my favorite.
I am on LM18.3 with cinnamon 3.6.7 (i7700, nvidia1050). We are using 6 computers at the office and all of them are on the latest LM18.3 with cinnamon 3.6.7.
Our computers are all upto date and sysmonitor@orcus works fine on all of them. All computers are running LM18.3 since LM17 and incremental system updates took them to LM18.
I have reinstalled LM18.3 as a brand new installation on one of the existing computers and I can not reinstall sysmonitor@orcus any more. I am suspicious about flatpack but not knowledgable enough to isolate the problem.How can I make sysmonitor work again? Any helpwill be appreciated.

**Comment by cevadoztug** [comment]
@OrcusCZ

**Comment by cevadoztug** [comment]
Traceback (most recent call last):
  File "/usr/bin/cinnamon-subprocess-wrapper", line 24, in <module>
    PushSubprocessResult(process_id, result, success)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
UnicodeError: String parameters to be sent over D-Bus must be valid UTF-8 with no noncharacter code points

**Comment by NikoKrause** [comment]
You could create an issue on this repo with some info, what's wrong and how to reproduce it.

**Comment by cevadoztug** [comment]
Ok @NikoKrause . Thank you for your attention.
To reproduce the case please just do the followings. (Those are what I did)
1. Install brand new LM18.3 Cinnamon x64 English on i7700,32 gb ram, nvidi 1050 gpu.
2. Check for Gir1.2 installation (I have Gir1.2-gtop-2.0 , Gir1.2-accounts-1.0 , Gir1.2-accountsservice-1.0 , Gir1.2-appindicator-0.1)
3. Add applet to Cinnamon bar. (First download sysmonitor@orcus 1.6.2 and add it to panel)

Congratulations you have reproduce the problem. (If you were updating your LM from earlier versions and if there were sysmonitor@orcus already there you wouldn,2t experience any problem.)

Result:
The usual graphic boxes are not there. 
There is an error message saying "Something went wrong while loading sysmonitor@orcus. Please make sure you are using the latest version and then report the issue to its developer."
Reboot generates the same error message and the applet is missing in the bar.

Any suggestions will be appreciated.

**Comment by NikoKrause** [comment]
@cevadoztug Pleas file a bug report here: https://github.com/linuxmint/cinnamon-spices-applets/issues
(There's a "New issue" button).

**Comment by NikoKrause** [comment]
What's the date (Last modified:) in the about dialog?

**Comment by cevadoztug** [comment]
2018-02-26 11:00 UTC.
I will report bug as you have suggested.
Thanks.

**Comment by cevadoztug** [comment]
Thanks a lot.
Problem solved.
Everything is working fine as it supposed to be.

**Comment by NikoKrause** [comment]
You're welcome.

**Pull request merged**
