### PR TITLE
directory-menu@torchipeppo: Add support for Flatpak terminals

### PR DESCRIPTION
**Pull request by rcalixte**
cc @torchipeppo This adds support for terminals installed via Flatpak (e.g. [Black Box](https://flathub.org/apps/com.raggesilver.BlackBox))

Shout if you want to change the version too.

### CODE REVIEW

**Review by torchipeppo — APPROVED** [review]
I see no issues with that.
Would you mind incrementing the patch version number?

**Comment by rcalixte** [comment]
> Would you mind incrementing the patch version number?

I assume 0.6 is okay?

**Comment by torchipeppo** [comment]
Sorry about the misunderstanding, by "patch" I meant the third number (which is not explicitly there at the moment), resulting in 0.5.1
But at this point I feel like I might be getting too pedantic over something ultimately inconsequential, so I'll be fine either way.

**Comment by rcalixte** [comment]
> Sorry about the misunderstanding, by "patch" I meant the third number (which is not explicitly there at the moment), resulting in 0.5.1 But at this point I feel like I might be getting too pedantic over something ultimately inconsequential, so I'll be fine either way.

It's fine! I'm glad I checked with you first. I just spaced on the semantic versioning myself so I'm glad to get it right according to your wishes.

**Comment by torchipeppo** [comment]
All good. I only thought about it because I read it on a whim semi-recently, too.
Anyway, thank you for the update! ^_^

**Pull request merged**
