### PR TITLE
cryptocoin@guantanamoe: unlimited instances and multiple coins

### PR DESCRIPTION
**Pull request by bkmeneguello**
- Enable multiple instances
- Each instance is a pair Coin/Crypto. The list of coins and cryptos is fixed

### CODE REVIEW

**Comment by jaszhix** [comment]
Let's ping @imDeprecated for review.

**Comment by imDeprecated** [comment]
Tested, I think some work needs to be done in the usability of the settings.  The long lists take a minute to load on my dev laptop (old thinkpad).

Also there seems to be loss in functionality due to only tracking one ticker now.

Tickers would need to be searchable and individually added to a tracked set in order to bring in an additional 4k of them.  I just don't see the usability in scrolling for 30 secs to get down to XRP

**Comment by bkmeneguello** [comment]
Well, about the long time, it really takes, but just a little delay for me. I'll search for a better way to list all cryptos without so much delay.
About the functionality loss, it's not missed, since now the applet allows multiple instances each with a different setting.
I've sorted the cryptos by its ticker name, to facilitate the search, since cinnamon combos are not searchable.

**Comment by bkmeneguello** [comment]
Fixed with free input

**Comment by NikoKrause** [comment]
@imDeprecated ?

**Comment by imDeprecated** [comment]
Sorry, approved

**Pull request merged**
