### PR TITLE
use correct function for custom css class

### PR DESCRIPTION
**Pull request by zagortenay333**

### CODE REVIEW

**Comment by NikoKrause** [comment]
@mockturtl

**Comment by mockturtl** [comment]
@zagortenay333 Thanks!

@collinss Please weigh in, I couldn't tell if this change was the best way to handle the issue.
Context: mockturtl/cinnamon-weather#175

**Comment by Odyseus** [comment]
Hello, everybody.

Using the **setCustomStyleClass** function directly as used by this PR will break the applet in all Cinnamon versions older that 3.2.x.

I use that function as follows to make it retro-compatible.

```javascript
if (typeof this.menu.setCustomStyleClass === "function")
    this.menu.setCustomStyleClass("menu-background");
else
    this.menu.actor.add_style_class_name("menu-background");
```

**Comment by zagortenay333** [comment]
@Odyseus Updated.

**Comment by zagortenay333** [comment]
Btw, I thought commits added in this repo would propagate to the spices-site quickly. Why is it taking so long?

**Comment by JosephMcc** [comment]
I thought they updated like every five minutes or something. I can try to find out if something is going on with it.

**Comment by NikoKrause** [comment]
I merged the applet about 18 hours ago here on GutHub.

Cinnamon Spices shows the last change for the weather applet also 18 hours ago.

As JosephMcc said, there's a script running, which checks every 5 Minutes for updates.

**Comment by zagortenay333** [comment]
Hmm, for some reason I had to uninstall the applet and reinstall it to get the latest change.

**Comment by NikoKrause** [comment]
Hmm....

Normally it suffices to hit the "Refresh list" button and then the "Updates available" button.

**Comment by zagortenay333** [comment]
Yeah, that didn't work.

**Pull request merged**
