### PR TITLE
[disk-read-and-write-speed@cardsurf] Add a new applet

### PR DESCRIPTION
**Pull request by cardsurf**
An applet that shows usage of a disk for Linux Mint Cinnamon

Disk read and write speed

[Original repository.](https://github.com/cardsurf/disk-read-and-write-speed)

### CODE REVIEW

**Comment by NikoKrause** [comment]
Please make the icon square.
I also see some unused imports.

**Comment by jaszhix** [comment]
I tested and I noticed there are no speed values when it is added to the panel.

.xsession-errors:

```
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/disk-read-and-write-speed@cardsurf/appletGui.js 454]: assignment to undeclared variable last_char
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/disk-read-and-write-speed@cardsurf/appletGui.js 455]: assignment to undeclared variable semicolon
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/disk-read-and-write-speed@cardsurf/cssStylization.js 21]: assignment to undeclared variable attribute_name
Cjs-Message: JS WARNING: [/home/jason/.local/share/cinnamon/applets/disk-read-and-write-speed@cardsurf/cssStylization.js 21]: assignment to undeclared variable attribute_value
Cjs-Message: JS LOG: Error while calculating disk read and write speed: ReferenceError: assignment to undeclared variable table
Cjs-Message: JS LOG: Loaded applet disk-read-and-write-speed@cardsurf in 181 ms
Cjs-Message: JS LOG: Error while calculating disk read and write speed: ReferenceError: assignment to undeclared variable table
Cjs-Message: JS LOG: Error while calculating disk read and write speed: ReferenceError: assignment to undeclared variable table
```
The last error continues to repeat until I remove the applet. I recommend not wrapping big chunks of code in try-catch blocks, so it is easier to catch these kinds of small mistakes. :)

**Comment by cardsurf** [comment]
@jaszhix Thanks for the help. 
Before making the pull request I tested the applet using a clean image of Linux Mint Cinnamon 18.2. I didn't see any warnings/errors in Looking Glass and the applet was running fine.

**Comment by jaszhix** [comment]
No problem. Unfortunately Looking Glass/Melange logging (~/.cinnamon/glass.log) doesn't show the logging from ~/.xsession_errors (also available with `cinnamon --replace`), and in some distributions with a different login manager, that file doesn't exist. CJS will warn or show more thorough errors in xsession_errors. Lately I've been modifying the logging function in ui/main so it dumps glass.log's output to xsession_errors, but something should probably be done about the split logging so all errors can be seen easily.

**Pull request merged**
