### PR TITLE
update func for setting custom css class

### PR DESCRIPTION
**Pull request by zagortenay333**

### CODE REVIEW

**Comment by NikoKrause** [comment]
@zagortenay333
It would be nice if you could mention the author @scollins in a PR to notify him and to use the uuid or name of the applet in the PR title.
This way it's easier to find stuff later.

**Comment by germanfr** [comment]
You forgot to remove this line there.
```js
this.menu.actor.add_style_class_name("xCenter-menu");
```

**Comment by zagortenay333** [comment]
@NikoKrause yeah, srry forgot that
@germanfr oh updated

**Comment by zagortenay333** [comment]
@collinss

**Comment by Odyseus** [comment]
@zagortenay333.

Same as in [this PR](https://github.com/linuxmint/cinnamon-spices-applets/pull/49#issuecomment-276496679).

**Comment by zagortenay333** [comment]
Fixed.

**Comment by mockturtl** [comment]
> use the uuid or name of the applet in the PR title.  This way it's easier to find stuff later.

Have you thought about using GitHub's issue labels?

**Comment by NikoKrause** [comment]
> Have you thought about using GitHub's issue labels?

It's easier, if everybody uses the uuid in the title at the first place, than for me setting the label for every issue/PR after it has been opened in the second place.

**Pull request merged**
