### PR TITLE
ratecurrency@magner

### PR DESCRIPTION
**Pull request by AleksiMagner**

### CODE REVIEW

**Comment by AleksiMagner** [comment]
I can not find how to discard the changes. Can I just delete the file, and then upload a new one again?

**Comment by Gr3q** [comment]
"git checkout <branch> -- README.md" command is for this.

Choose a branch what you know has the original version of the file. (for example master should not have any changes for you)

So If you run "git checkout master -- README.md" you should see (hopefully) that the file is reverted, then you can commit and push it.

**Comment by AleksiMagner** [comment]
I uploaded directly through the site, without a terminal. Through the terminal, I have not worked with GitHub yet. At the moment, just deleted the ReadMe.md file.
Is this enough for approval? Or should I close the PR and upload everything again?

**Comment by AleksiMagner** [comment]
In the terminal, when git is cloned, only the master branch is downloaded, there is no access to others. And in the master branch there is no my applet, therefore I can’t do anything through the terminal either

**Comment by Gr3q** [comment]
Still incorrect, you deleted the file instead of revert the changes.

Now, you can either recreate the same file (README.md) with [this](https://raw.githubusercontent.com/linuxmint/cinnamon-spices-applets/be78505ce02bba138cb616365293a233535c0488/README.md) content.

Or learn git (github is just a place where people upload their git repositories) which is not really hard.

**Comment by AleksiMagner** [comment]
I will create a new one fixed. Files cannot be recovered

**Comment by Gr3q** [comment]
1. You first need to Fork this repository (by clicking Fork at the top), so you have a copy you can freely edit
2. Visit your Fork on your account, then git clone that.
3. Now you can use a git gui (like GitKraken or SmartGit) or you use the terminal. gui is usually easier when you start out.
4. Create a new branch ```git branch <your-feature>```
5. Switch to your new branch ```git checkout <your-feature>```
6. Set the upstream for the branch ```git branch --set-upstream-to origin/<your-feature>```
7. Create new files, add your feature and stuff (everything is tracked)
8. Stage all new files and changes ```git add -A```
9. Commit your changes ```git commit -m <What feature does as a short description>```
10. Push you changes to your actual fork ```git push```

Then you can actually create a PR from that easily on github. If you want to add more stuff, do stuff from number 7. again to add to your PR.

**Comment by AleksiMagner** [comment]
Thank you very much. This instruction helped a lot. Confused in switching branches at the beginning, so it didn’t work. In step 6, your team didn’t work, instead of it, git push --set-upstream origin <your-feature> worked
It would be nice to add this instruction to the README.md file of this repository

**Pull request closed without merging**
