### PR TITLE
power-profiles@rcalixte: Initial release of a power-profiles-daemon applet

### PR DESCRIPTION
**Pull request by rcalixte**
Closes linuxmint/cinnamon#10634

### CODE REVIEW

**Comment by haggen88** [comment]
@rcalixte If you want, you can include the Spanish translation:

[es.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/11133563/es.po.zip)

**Comment by rcalixte** [comment]
@haggen88 ¡Muchas gracias!

**Comment by rcalixte** [comment]
@brownsr This is also ready to merge. (I rebased with the fix commits so that it would build a few days ago but can rebase again if desired.)

**Comment by rcalixte** [comment]
@brownsr This is ready to merge. Thank you!

**Comment by rcalixte** [comment]
@brownsr @Cobinja @mtwebster This is ready to merge. Please shout if anything else is needed. Thank you!

**Comment by rcalixte** [comment]
Ping @brownsr

**Comment by rcalixte** [comment]
ping @clefebvre @brownsr @mtwebster

**Comment by cassepipe** [comment]
Thanks @rcalixte :pray:

**Pull request merged**
