### PR TITLE
Hungarian Translation for Cinnamon Applets starting with the letter C

### PR DESCRIPTION
**Pull request by bossbob88**
Hello everyone,

these are the Hungarian hu.po files for every Cinnamon applet starting with the letter C.

### CODE REVIEW

**Comment by brownsr** [comment]
Unfortunately the back-up state applet has just been removed.  Could you remove this translation ?

Regards

Simon

**Comment by bossbob88** [comment]
> Unfortunately the back-up state applet has just been removed. Could you remove this translation ?
> 
> Regards
> 
> Simon

Hello Simon,
sure! I'm new to guthib, what is the best way to delete it? 
Should I go into bossbob88/cinnamon-spices-applets/back-up_state@natsakis.com/ and click on the three vertical dots button and choose delete directory and then do another pull request?

**Comment by brownsr** [comment]
Let's see how it works if I delete directly ...

**Comment by brownsr** [comment]
Well that didn't go too well.. but never mind, I could delete after the merge and all is well.

Regards

Simon

**Comment by bossbob88** [comment]
Ok! Let me know if it would not work out and should do anything.
Going, forward, I guess I need to delete that directory anyway, if I'm planning to make future pull request from my applet repository.

**Pull request merged**
