### PR TITLE
[Cinnamenu@json] Replaced user-info icon + bug fixes.

### PR DESCRIPTION
**Pull request by fredcw**
-Swapped user-info button with system-settings button.
-Removed ability to change order of categories.
-A few bug fixes.

### CODE REVIEW

**Comment by claudiux** [comment]
Hi @fredcw,

"-Removed ability to change order of categories."

Why? Why? Why?
This feature was very useful! Why destroy it?
Please restore it.

**Comment by smurphos** [comment]
I'd agree with @claudiux - one of cinnamenu's better features.

My use case - if the applet is on a top panel I want favourites at the top of the category list, if it's on a bottom panel I want it at the bottom. 

Also a shame you got rid of search-provider management rather than fixing it, but that probably was a very niche feature.

**Comment by fredcw** [comment]
@claudiux @smurphos I removed it because it removed about 150+ lines of complex code and I didn't think anyone would use it anyway. Also the menu now opens on whichever category the menu was open on previously so I still don't quite understand the use case. Would an option to always open the menu on favourites solve the problem?

I mean I could put it back but if few people use it then it just increases the maintenance burden.

**Comment by claudiux** [comment]
@fredcw Please, restore the capability to move the categories. This is a feature that many new Linux Mint users (who previously used another operating system) like.

**Comment by fredcw** [comment]
@brownsr On the cinnamon applets website (https://cinnamon-spices.linuxmint.com/applets/view/322) it says that the last commit was 2 days ago (#3069), i.e. this one. But when you download the applet or install the latest version directly from cinnamon applets list, the version installed is the previous version (#3057) from 9 days ago. Do you have any idea why it hasn't updated yet? I assumed that if the applets website says that the last commit was #3069, then the downloadable version would be updated at the same time.

**Comment by fredcw** [comment]
@claudiux @smurphos I've put the category reordering back. Thanks for the feedback.

**Comment by claudiux** [comment]
Many thanks, @fredcw, that is really cool!

I had an error just after updating Cinnamon:
```
Cjs-Message: 20:16:05.134: JS LOG: [LookingGlass/info] Reloading applet: Cinnamenu@json/132

(cinnamon:3123): St-CRITICAL **: 20:16:05.322: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Cinnamon warning: Log level 8: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Cjs-Message: 20:16:05.624: JS LOG: [LookingGlass/error] Could not find setting key 'categories' for xlet Cinnamenu@json
Cjs-Message: 20:16:05.664: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function 844]: reference to undefined property "categories"
Cjs-Message: 20:16:05.664: JS LOG: [LookingGlass/error] 
[Cinnamenu@json]: this.state.settings.categories is undefined
[Cinnamenu@json]: Failed to evaluate 'main' function on applet: Cinnamenu@json/132
Cjs-Message: 20:16:05.664: JS LOG: [LookingGlass/trace] 
<----------------
initCategories@/home/claude/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js:844:1
CinnamenuApplet@/home/claude/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js:172:9
main@/home/claude/.local/share/cinnamon/applets/Cinnamenu@json/4.0/applet.js:2077:12
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:581:18
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:356:22
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:95:14
Extension.prototype._init/<@/usr/share/cinnamon/js/ui/extension.js:277:17
---------------->
Cjs-Message: 20:16:05.665: JS LOG: [LookingGlass/error] 
[Cinnamenu@json]: Applet Cinnamenu@json: Could not create applet object.
[Cinnamenu@json]: Error importing applet.js from Cinnamenu@json
Cjs-Message: 20:16:05.665: JS LOG: [LookingGlass/trace] 
<----------------
Extension.prototype._init/<@/usr/share/cinnamon/js/ui/extension.js:278:23
---------------->
```
Cinnamenu crashed!

A Cinnamon restart solved the problem.

**Comment by fredcw** [comment]
@claudiux I think you must have upgraded the applet by downloading it and copying it to your applets folder manually. This is fine of course but cinnamon remembers your applet settings, assumes that the applet hasn't changed and doesn't reread the new settings-schema.json file until it's restarted. I can't think of a good way to fix this but thanks for the bug report it's something I hadn't considered before.

**Comment by claudiux** [comment]
@fredcw No, I used Spices Update, off course, which restart the applet once it was updated.

**Comment by fredcw** [comment]
@claudiux ah, so cinnamon doesn't reload the settings-schema file when it updates an applet then. I see you wrote spices update so you must know far more about cinnamon than I do. I can't find any documentation for cinnamon so I basically have no idea how the api works. How do you avoid this problem?

**Comment by fredcw** [comment]
@claudiux I fixed it I think. The problem was with the applet, not cinnamon.

**Comment by fredcw** [comment]
@smurphos I'm not sure what you mean by broke as cinnamenu seems to provide the same provider results as the main cinnamon menu. And actually, I can't seem to get any provider results in mint any more (19.3 & 20) anyway, either in cinnamenu or the main cinnamon menu. I get results in manjaro (only the wikipedia and calculater results)

**Comment by smurphos** [comment]
@fredwc - previously, when you toggled enabled search-providers in the config the config would show a list of the available search-providers on the system and allowed the end-user to enable/disable individual searchproviders. There's no point have the toggle or the example search providers button without that UI

**Pull request merged**
