### PR TITLE
Puts uncategorized timezones into the list of World Clocks

### PR DESCRIPTION
**Pull request by sphh**
Includes uncategorized timezones in the list of World Clocks. (Issue #3314)

### CODE REVIEW

**Comment by brownsr** [comment]
ping @ccprog

**Comment by ccprog** [comment]
Thank you for your work on this. This is the right direction.

There are actually more occurrences where you need to take care of string splitting: lines 57, 71 and 78. Currently, after setting the UTC timezone, the settings window won't open again.

I would propose a utility function `split_name`:

```python
def split_name(str):
    try:
        r, c = str.split('/', maxsplit=1)
    except ValueError:
        r = TZ_NO_CATEGORY
        c = str
    return r, c
```

**Comment by ccprog** [comment]
You should propose the same sort of change to the Cinnamon Date and Time Settings dialog, which my settings code was inspired from. Having different lists for timezones in different dialogs would be confusing.

https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_calendar.py

Especially, the "Miscellaneous" string should be the same in both use cases, should they accept the change.

**Comment by sphh** [comment]
@ccprog: You are right, I missed the other occurrences of the splitting code (that's why I didn't make a dedicated method for it). Thanks for pointing that out. I also changed the `'Miscellaneous'` string to `'Etc'`, because that's what `pytz` uses.

@brownsr: What do you think of @ccprog's suggestion? If you also think, that's a good idea, I can create a PR along the same line as for this applet.

**Comment by ccprog** [comment]
Resolves #3314. Please merge.

**Comment by brownsr** [comment]
Feel free to propose the PR to the main cinnamon code.  It won't be me reviewing or merging though, so I can't say if it will be accepted.

Regards

Simon

**Pull request merged**
