### PR TITLE
xsession@claudiux - v1.0.0

### PR DESCRIPTION
**Pull request by claudiux**
Hi,

This a new Applet, useful for debugging Spices.

Can you merge this branch with your master one, please?

Regards.
Claudiux

### CODE REVIEW

**Comment by haggen88** [comment]
@claudiux If you want you can include the Spanish translation
> 
[es.po.zip](https://github.com/linuxmint/cinnamon-spices-applets/files/10329721/es.po.zip)

**Comment by claudiux** [comment]
@haggen88 
Thank you! Your Spanish translation is now included.

**Comment by claudiux** [comment]
Hi @brownsr,

I have nothing to add. Can you merge this branch, please?

Regards.
Claudiux

**Comment by claudiux** [comment]
Is there a problem with this applet?

**Pull request merged**
