### PR TITLE
 cinnamon-timer@jake1164 - v1.1.0 - Moved settings into cinnamon-settings.

### PR DESCRIPTION
**Pull request by jake1164**
See README.md for additional functionality.

### CODE REVIEW

**Comment by NikoKrause** [comment]
Hey @jake1164 

wouldn't it make more sense, if you used a Combobox as Unit in Preset Times?

**Comment by NikoKrause** [comment]
Nevermind. Just realized there is no combobox within the list type

**Comment by jake1164** [comment]
It would, however, I was not able to get it working in the "list" columns.   My understanding (based on the [code](https://github.com/linuxmint/Cinnamon/blob/c72daa2e0e06a2a9e7069f621667ae938c731e32/files/usr/share/cinnamon/cinnamon-settings/bin/TreeListWidgets.py)) is the current supported types are:
    "string"        :   Entry,
    "file"          :   FileChooser,
    "icon"          :   IconChooser,
    "sound"         :   SoundFileChooser,
    "keybinding"    :   Keybinding,
    "integer"       :   SpinButton,
    "float"         :   SpinButton,
    "boolean"       :   Switch

**Comment by jake1164** [comment]
FYI, I did add a request to cinnamon to add support for a combobox.
https://github.com/linuxmint/Cinnamon/issues/6970

**Comment by NikoKrause** [comment]
I thought about it. Instead of having a `string: Unit (seconds, minutes, hours)` you can use three integers (Just an idea):

screenshot-window-2017-11-07-193251

**Comment by jake1164** [comment]
That's a good workaround, thanks for the idea!

**Pull request merged**
