### PR TITLE
weather@mockturtl 2.1.1 Update - OpenWeatherMap no longer requires key

### PR DESCRIPTION
**Pull request by Gr3q**
By the courtesy and support of OpenWeatherMap.

Fixes and Changes: 
* Forcing mainloop to refresh when Weather update fails (it was not updating for a whole refresh interval when we had a successful update then the settings was changed right after and update failed)
* Using Regex against Location setting
* DarkSky error messages are displayed properly to the users now
* Fixed some OpenWeatherMap json response error handling (it was matching strings to numbers)
* Removed obsolete code
* Edited Readme
* Added some thanks to OpenWeatherMap at the bottom of the settings

### CODE REVIEW

**Comment by Gr3q** [comment]
After this I'll probably slow down with the feature updates, if probably fixing bugs when they come up and stuff (If someone needs a popular API integration maybe that).

Also, can someone explain what I'm doing wrong with the translations, I feel like I'm doing more damage than help.

**Comment by Gr3q** [comment]
Please hold off with the release, I need to add more debug logging

**Comment by Gr3q** [comment]
@jaszhix It is ready, please pull when you are ready so people can have access for the previous version as well for now.

**Comment by dopeboy** [comment]
@Gr3q so cool to see you persisting with this applet. Shall I clean it up now that no key is required? I can kill the field and clean up the docs.

**Comment by Gr3q** [comment]
@dopeboy what cinnamon version are you running?

**Comment by dopeboy** [comment]
Cinnamon 3.8.8 and 2.0.0 of the applet. Just installed it last night on a new laptop.

**Comment by Gr3q** [comment]
We are on 2.1.6 atm, so have a look at that and see what you'd like to change

**Pull request merged**
