### PR TITLE
hwmonitor@sylfurd : New graphs - Net in and out

### PR DESCRIPTION
**Pull request by Hultan**
* Two new graphs, net in and out
* Ability to hide all graphs
* Ability to size all graphs independently
* New detail labels on the graphs (showing CPU usage % etc)
* Ability to change font sizes

### CODE REVIEW

**Comment by claudiux** [comment]
What a good work! Thank you @Hultan.

**Comment by Hultan** [comment]
Thank you @claudiux :-)

A question about spices-update@claudiux though. I don't understand how the process works, on my Linux Mint machines I got the new version of hwmonitor@sylfurd last night (almost immediately) through spices-update. On my main machine, running Manjaro Cinnamon, I still haven't got the new version through spices-update. Sure I could easily use my "code-version" but then I will get messages in spices-update that tells me to update it to the "old" version since my "code"-version does not match the "old"-version?

Yesterday evening I got one of those messages, and I updated hwmonitor and I got the old version back (which I could easily update manually though). I just want to understand, how Manjaro can be behind Mint everytime?

I am still learning about Linux/Cinnamon and versions, so there is definitely something I have not yet understood here :-)

**Comment by claudiux** [comment]
Hi @Hultan,

Please try with the v4.0.1, installing it manually using the method described here: https://cinnamon-spices.linuxmint.com/applets/view/309#count

Friendly.
Claudiux

**Comment by Hultan** [comment]
Hi @claudiux,

When I do so, the new version is 4.0.0, and when I hit refresh it wants to update SpicesUpdate and if I do it reverts back to 3.x? Weird...:-)

**Comment by Hultan** [comment]
I should say though that hwmonitor now is updated through SpicesUpdate, the update came a few hours ago.

**Comment by claudiux** [comment]
@Hultan Please use this link to download version 4.0.1: https://cinnamon-spices.linuxmint.com/files/applets/SpicesUpdate@claudiux.zip?84e821c1-7ff5-4fd8-a833-f8d399a51582

Restart Cinnamon after installation.

By using Spice Update you should no longer have this kind of inconvenience.

**Comment by Hultan** [comment]
That seemed to fix it, the notification went away...thanks @claudiux ...

**Pull request merged**
