### PR TITLE
Update metadata.json

### PR DESCRIPTION
**Pull request by Padre2**
Change max-instances from 3 to 1 to prevent crashing Cinnamon 4.4.3

### CODE REVIEW

**Comment by claudiux** [comment]
@mockturtl

**Comment by Gr3q** [comment]
I do not think that this is the right way to solve the issue, this only works around the problem that the applet manager does not enforce max-instance setting correctly nor it prevents the user to spam the Add button. 

The issues related to the applet manager should be raised in the main cinnamon repo [here](https://github.com/linuxmint/cinnamon/issues) first as it affects all applets.

Also giving users the option to have multiple weather applets is a feature already enabled for the applet, and I usually vary to take features away even they are broken (I'm pretty sure we will break at least a few people's workflow disabling it).

 If the others think the feature should be disabled for the weather@mockturtl applet, then I won't say no either.

**Comment by Padre2** [comment]
@Gr3q  @mockturtl @claudiux
I have only recently started using Linux and am trying to get up to speed with Arch and my chosen DE Cinnamon. I am getting the latest updates daily and Cinnamon is already at version 4.4.3, whereas even Manjaro (Arch) is still on Cinnamon 4.2.4.

An objection to removing the ability to allow users to load multiple instances of this Weather applet is puzzling. I cannot conceive of any need to display 2 or 3 instances of this applet on a desktop panel. What am I missing?

I must accede to your decision,  because my knowledge of the coding in Cinnamon is very limited and this is my first PR.  As far as raising this issue in the the main Cinnamon repo, I will leave this to you, as I don't understand how this change would affect all applets.  This is a popular applet and I think there will be a more issues raised as other distros catch up. I have had no issues at all with Weather since I made the suggested change, so will be ok until there are updates.

**Comment by mockturtl** [comment]
>  I cannot conceive of any need to display 2 or 3 instances of this applet on a desktop panel.  What am I missing?

Some users like to know the weather in multiple cities.  I can imagine a better interface to support it, but multiple instances are an easy workaround.

Likewise, if multi-instance is broken in a recent Cinnamon release, editing the metadata file feels like a "hotfix" until the underlying problem is resolved.

I suggest we use votes on this PR to decide which is causing more pain.  In any case, it will help if someone with more information [opens an issue upstream](https://github.com/linuxmint/cinnamon/issues).

**Comment by Padre2** [comment]
@mockturtl
> Some users like to know the weather in multiple cities. I can imagine a better interface to support it, but multiple instances are an easy workaround.
> 
> Likewise, if multi-instance is broken in a recent Cinnamon release, editing the metadata file feels like a "hotfix" until the underlying problem is resolved.
> 
> I suggest we use votes on this PR to decide which is causing more pain. In any case, it will help if someone with more information [opens an issue upstream](https://github.com/linuxmint/cinnamon/issues).

Ok, now I understand.  No problem for me right now, if not merged. We can wait and see how this develops.

**Comment by Gr3q** [comment]
https://github.com/linuxmint/cinnamon/issues/9004 opened

**Comment by Padre2** [comment]
@mockturtl
> Some users like to know the weather in multiple cities. I can imagine a better interface to support it, but multiple instances are an easy workaround.
> 
> Likewise, if multi-instance is broken in a recent Cinnamon release, editing the metadata file feels like a "hotfix" until the underlying problem is resolved.
> 
> I suggest we use votes on this PR to decide which is causing more pain. In any case, it will help if someone with more information [opens an issue upstream](https://github.com/linuxmint/cinnamon/issues).

Ok, now I understand.  No problem for me right now, if not merged. We can wait and see how this develops.

**Comment by brownsr** [comment]
Closing as any issue appears to lie elsewhere.

**Pull request closed without merging**
