### PR TITLE
Update translation for Network Data Usage Monitor

### PR DESCRIPTION
**Pull request by giwhub**
@pdcurtis

### CODE REVIEW

**Comment by pdcurtis** [comment]
Thanks - Agreed

**Comment by NikoKrause** [comment]
@giwhub If it was me, you don't need 3 separate commits for that. What do you think pdcurtis?

**Comment by giwhub** [comment]
How to combine commits?
I am using Github web page version.

**Comment by NikoKrause** [comment]
Ah. You don't use git? I always thought you did this on purpose. 
Then nevermind. I can combine them, when I merge them

**Comment by giwhub** [comment]
I don't use git often.
Git clone/git push larger sources/lots of files from/to Github is very slowly in China.

**Comment by pdcurtis** [comment]
I have used git rebase with the -I option in the terminal which is very powerful after @NikoKrause suggested I combined commits.  
I have also  been looking at using an Android pad when Mobile with Mgit Droidedit and Forkhub so I am interested in any ways of working without a heavy laptop using WiFi in a pub or coffee shop. I had not thought about github on-line tools for coding but it is excellent in offering this sort of conversation. I can also see the advantages with some long collaborative developments during a PR, the vertical panel needed to merge over a hundred commits - three should be easy.

I think it very important to test even after what seems the most trivial change - I have been burnt too often.

**Comment by NikoKrause** [comment]
I thought you use git and it's more work for you to create a commit each time, I just wanted you to know, that one commit would suffice.
But since it's not the case you can keep your workflow. I'll squash them on merge or not. It's no big deal. Actually it's no big deal to squash on merge. It's just pressing a different button.

**Pull request merged**
