### PR TITLE
weather@mockturtl: small fixes to ru.po

### PR DESCRIPTION
**Pull request by Ilis**

### CODE REVIEW

**Comment by NikoKrause** [comment]
I'm not sure. Длина is length and Горизонт is the horizon.
And the string says, how many days should be shown. I'm not sure what this has to do with the horizon?
```
-msgstr "Длина прогноза"
+msgstr "Горизонт прогноза"
```
I'm no native speaker though.
@andreevlex What do you mean?

**Comment by Ilis** [comment]
Well, it is more specific term in Russian about weather forecast.

http://translate.academic.ru/%D0%93%D0%BE%D1%80%D0%B8%D0%B7%D0%BE%D0%BD%D1%82%20%D0%9F%D1%80%D0%BE%D0%B3%D0%BD%D0%BE%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F/ru/

горизонт прогнозирования = forecasting time-frame

In Russian we also use literally:
“forecast depth” or “forecast longitude”, not “forecast length”, because length is not property of Time.

But Horizon, instead, used for Time, such as “event horizon”

I'm sure, that “Горизонт прогноза” much better and well known for Russian speaking ppl, but “Длина прогноза” is not appropriate.

**Comment by NikoKrause** [comment]
Ah. Learned something New :)

**Comment by NikoKrause** [comment]
@mockturtl fyi

**Comment by mockturtl** [comment]
Спасибо

**Pull request merged**
