### PR TITLE
vboxlauncher@mockturtl: Add running indicator for vbox vms

### PR DESCRIPTION
**Pull request by xearonet**

### CODE REVIEW

**Comment by jaszhix** [comment]
Pinging @mockturtl

**Comment by mockturtl** [comment]
Please give me a couple weeks and ping me again.  I'm insanely busy just now.

**Comment by jaszhix** [comment]
There's never any expectation to do things right away (or at all), its just informational. I understand, this is outside my work as well. Whenever its convenient for you. :+1:

**Comment by jaszhix** [comment]
@xearonet Can you submit your changes to ioDisk@ctrlesc as a separate PR? You will need to drop the last commit or revert it (`git revert <hash>`) from this branch. I recommend not using your master branch, and submitting PRs from separate branches.

**Comment by xearonet** [comment]
Done. I create separate PR. 
Excuse that, I'm pretty new in GIT.

**Pull request closed without merging**
