### PR TITLE
cinnamon-timer@jake1164 - Changed settings to use individual hour, min and sec times.

### PR DESCRIPTION
**Pull request by jake1164**

### CODE REVIEW

**Comment by NikoKrause** [comment]
If I were you I would change order second,minutes,hours to hours,minutes,seconds.
Seems more natural to me.

Also I would add a range (min/max) for seconds and minutes from 0 to 59.

**Comment by jake1164** [comment]
excellent points, I'll make those changes in a few hours.  I am guessing I should also re-run the pot script now that I think about it?

**Comment by NikoKrause** [comment]
Yeah, if it contains new Strings to translate

**Comment by jake1164** [comment]
@NikoKrause done.

**Pull request merged**
