### PR TITLE
Updated Bulgarian Translation

### PR DESCRIPTION
**Pull request by angelzl**
Updated Bulgarian Translation using the latest translation template.

### CODE REVIEW

**Comment by angelzl** [comment]
Hi,

I've just completed the Bulgarian translation and updated the applet to the latest version so the new bg.po file is included (I do see the new file in ~/.local/share/cinnamon/applets/weather@mockturtl/po with the right content). Upon reloading the applet, however, the translation strings are not considered and what is displayed is an outdated and incomplete translation.

Is there anything else that needs to be done in order for this to work correctly?

**Comment by Odyseus** [comment]
Hello, @angelzl.

If you updated your applet from the Applets manager, then all new translations should have been installed too. I don't remember if after this Cinnamon needs to be restarted.

If you installed your applet manually (by extracting it into its final location), then you need to install the translations manually too. Running the command `cinnamon-xlet-makepot -i` from a terminal opened inside the xlet folder will install the translations and after restarting Cinnamon the xlet should start using the new translations.

**Comment by angelzl** [comment]
Hi @Odyseus,

I updated the applet from the Applets manager and see the updated bg.po file appear in the  ~/.local/share/cinnamon/applets/weather@mockturtl/po folder. I did restart Cinnamon but the translations are still not considered.

Out of curiosity, I renamed one of the other .po files from the folder mentioned above to bg.po and replaced my file to see if it will work with those translated strings (I did restart Cinnamon when I did that). It didn't.

Appreciate your help.

**Comment by Odyseus** [comment]
@angelzl: I found the cause of your problem. Your translation file (bg.po) has 2 fatal errors that prevent it from being installed.

```shell
~/home/odyseus~~/.local/share/cinnamon/applets/weather@mockturtl/po/bg.po:1:2: syntax error
~/.local/share/cinnamon/applets/weather@mockturtl/po/bg.po:745:62: syntax error
msgfmt: found 2 fatal errors
```

The first error must be the language itself being a b*tch (LOL). And the second error is an unescaped double quote at line 745 column 60.

I would recommend you that you to use POEdit for working with PO files. After fixing the file (I just opened and saved it using POEdit) it installed correctly.

**Just an FYI:** The xlet translations won't work by just placing the `.po` files inside the correct path inside the xlet folder. The content of the **po** folder (all the `.po` files) needs to be installed into your system (example: ~/local/share/locale/bg/LC_MESSAGES/XLET_UUID). That should happen automatically when installing/updating xlets from the respective xlet managers.

**Comment by angelzl** [comment]
Thanks you so much! Are you going to merge the updated file into the master branch?

Appreciate the FYI as well!

**Comment by Odyseus** [comment]
I'm not one of the *merger guys* (LOL). You can just open a new pull request and it will be reviewed and merged by the corresponding people.

**Pull request merged**
