### PR TITLE
[Cinnamenu@json] Add option run application on Nvidia GPU when render offload is available.

### PR DESCRIPTION
**Pull request by basilky**
Added 'Run with Nvidia' option to application right click menu, similar to Mint menu.

### CODE REVIEW

**Comment by brownsr** [comment]
ping @fredcw

**Comment by fredcw** [comment]
@basilky Nice, thanks. @brownsr this PR can be merged. Thanks.

**Comment by fredcw** [comment]
@basilky Yes, I didn't see that. I don't have an Nvidia gpu to test it but it looks fine. Also, for future reference, you don't have to make changes to the 3.2 version if you don't want to. I haven't made any changes to it because I have no easy way to test them and I'm guessing that not many people are still using cinnamon < v4.x with cinnamenu. Thanks.

**Comment by basilky** [comment]
@fredcw Thanks for the information. The changes are perfectly working for me. I hope its ready to merge.

**Pull request merged**
