### PR TITLE
Add Chinese translation for GPaste Reloaded and Sticky Notes

### PR DESCRIPTION
**Pull request by giwhub**
Add Chinese translation for GPaste Reloaded and Sticky Notes.

### CODE REVIEW

**Comment by collinss** [comment]
@feuerfuchs are you ok with this new translation?

**Comment by Feuerfuchs** [comment]
I am! Thanks for the translation @giwhub. :)

**Comment by giwhub** [comment]
You're welcome.

**Comment by collinss** [comment]
@giwhub Thanks for using separate commits for each applet. In the future it might be helpful to use a separate pr for each author. It was fine here because the other author was me, but the more authors that have to approve, the longer it takes, and the harder it is to keep track.

**Comment by giwhub** [comment]
Thanks to let me know that,I will use separate commits for each applet next time.

**Pull request merged**
