### PR TITLE
applet.js

### PR DESCRIPTION
**Pull request by joshbowyer**
This applet was abandoned and was never updated to work with SystemD. I updated and thoroughly tested it and it now works with SystemD, with the only necessary changes being in this js file.

### CODE REVIEW

**Comment by joshbowyer** [comment]
Had to redo it since I uploaded the wrong file/revision....

**Comment by jaszhix** [comment]
Please take a look at the readme, it explains the file structure needed for Cinnamon to be able to load it, and for the website to display it correctly. 

I'm not able to test this because it doesn't have a metadata.json file.

**Comment by joshbowyer** [comment]
I'm a little confused. All that needs to be done is replace the current applet.js with the proposed one. I don't really use git, but shouldn't you be able to test by just installing the current spice and then overwriting the local applet.js file in ~/.local/share/cinnamon/applets ?

-------- Original Message --------

**Comment by jaszhix** [comment]
Oh I see, I figured it was removed at some point because it was a file addition in the diff. Yeah, applet.js needs to be modified instead.

**Pull request closed without merging**
