### PR TITLE
Turkish translation update for Radio3.0@claudiux

### PR DESCRIPTION
**Pull request by serkan-maker**

### CODE REVIEW

**Comment by claudiux** [comment]
Thank you very much @serkan-maker !

Instead of including all the screenshots in the applet, could you post them to a Github folder, like I did here? https://github.com/claudiux/docs/tree/master/Radio3.0/screenshots 

Otherwise, this applet may become too cumbersome to download.

You did a great job! Indeed!

**Comment by serkan-maker** [comment]
hi.
I cloned and added your repository. I hope it was correct
https://github.com/serkan-maker/docs/tree/master/Radio3.0/screenshotsTR

**Comment by claudiux** [comment]
That seems ok. Can you make a Pull Request, please?

**Comment by brownsr** [comment]
There's a huge amount of translation collateral here. Screen shots, translations of the manual ... Much more than the typical pot file. @serkan-maker @claudiux are you both content this PR is merged following your discussions ?

Regards

Simon

**Comment by claudiux** [comment]
@brownsr 
Hi Simon,

Screenshots will be stored on my github space to avoid overloading the applet. It's also possible that all MANUAL.md and MANUAL.html are too, if you prefer; but it will be more complicated to verify their existence. The help-text.js file has become useless; I will delete it. I don't want this applet to be too heavy to download.

Are you OK?

Regards.

**Comment by serkan-maker** [comment]
I made the necessary corrections and created a pull request.

**Pull request merged**
