### PR TITLE
[ssm@Severga] Improve net list update

### PR DESCRIPTION
**Pull request by Severga**
It turned out that the applet's list of net interfaces is shown incorrectly after turning off and on some connections in Network Manager. The signals I was able to find and use do not cover all changes that happen and the list sometimes doesn't change automatically, except after reloading the applet. Instead of signals I decided to use periodical net interfaces look-up every 30 sec.

I understand that this is not an efficient solution, and if somebody can help me with the signals, I would appreciate it very much.

### CODE REVIEW

**Comment by rcalixte** [comment]
Which signals? And have you taken a look at the other KDE Connect applet's code?

**Comment by Severga** [comment]
I meant NMClient's "device-added", "device-removed", "connection-added", "connection-removed".

**Comment by Severga** [comment]
@rcalixte, I rewrote the applet.js. Now it works good. Please, apply these changes.

**Comment by rcalixte** [comment]
> @rcalixte, I rewrote the applet.js. Now it works good. Please, apply these changes.

Congrats! Sorry I didn't have a chance to dig into the signals but I'm glad you got it figured out!

**Comment by rcalixte** [comment]
> @rcalixte, I rewrote the applet.js. Now it works good. Please, apply these changes.

Do you want to add a version in the metadata? It may help with troubleshooting if there are any problems.

**Comment by Severga** [comment]
@rcalixte, to tell the truth, I know nothing about applets' version system. I'm not a professional coder, I have little time for my hobby, and I write small applets right in my simple text editor. So... I even don't know what to say, sorry.. :)

**Comment by rcalixte** [comment]
> @rcalixte, to tell the truth, I know nothing about applets' version system. I'm not a professional coder, I have little time for my hobby, and I write small applets right in my simple text editor. So... I even don't know what to say, sorry.. :)

No stress. 😄

**Review by rcalixte — APPROVED** [review]

**Pull request merged**
