### PR TITLE
[Sensors@claudiux] v3.1.0 - Fixes issues for Manjaro and Arch

### LINKED ISSUE #4917: [Sensors@claudiux] smartctl permission denied
* Applet version/Build date: Version 3.0.3 (2023-06-27 21:58:29)
 * Cinnamon version: Cinnamon 5.8.3
 * Distribution: Arch
 * Graphics hardware *and* driver used: NVIDIA GM107GLM [Quadro M1000M], nvidia 535.54.03
 * Snippet or attachment of ~/.xsession-errors:
```
Gjs-Message: 16:19:26.116: JS LOG: [LookingGlass/error] File »/etc/sudoers.d/smartctl« konnte could not be opened: Permission denied
Gjs-Message: 16:19:26.116: JS LOG: [LookingGlass/trace]
<----------------
is_disktemp_user_readable@/home/tilo/.local/share/cinnamon/applets/Sensors@claudiux/applet.js:221:37
get_user_settings@/home/tilo/.local/share/cinnamon/applets/Sensors@claudiux/applet.js:213:55
SensorsApplet@/home/tilo/.local/share/cinnamon/applets/Sensors@claudiux/applet.js:106:10
main@/home/tilo/.local/share/cinnamon/applets/Sensors@claudiux/applet.js:1352:10
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:597:25
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:372:34
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:309:26
---------------->

(cinnamon:1132): Gjs-CRITICAL **: 16:19:26.121: JS ERROR: Error: [Applet] Unable to find definition for applet undefined
_getPanelInfo@/usr/share/cinnamon/js/ui/applet.js:225:19
_init/<@/usr/share/cinnamon/js/ui/applet.js:201:35
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

```

**Notify author of applet**
@claudiux 

**Issue**

Since the latest update, the applet fails to start, configuration dialogue works though

**Steps to reproduce**

Install the applet and add it.

**Expected behaviour**

It continues to work just like before

**Other information**

That file doesn't even exist for me

### PR DESCRIPTION
**Pull request by claudiux**
Fixes issues flagged by Nitrooo on: https://cinnamon-spices.linuxmint.com/applets/view/337#count
Fixes #4917

### CODE REVIEW

**Comment by claudiux** [comment]
Ping @Nitrooo

**Comment by Nitrooo** [comment]
The fix works fine. However, I've just noticed that disk temperatures are not shown in the tooltip unless you also set them to be shown in the panel. I do not know if this problem was introduced with this fix because I have not tested this feature before. In any case, thank you for the fix and for your great work.

**Comment by claudiux** [comment]
> I've just noticed that disk temperatures are not shown in the tooltip unless you also set them to be shown in the panel.

You're right. I will fix this new issue.

**Comment by claudiux** [comment]
@Nitrooo Tooltip error fixed now.

**Comment by claudiux** [comment]
Put in WIP. I'm not entirely satisfied with the result.

**Comment by claudiux** [comment]
This is better and ready to merge.

**Pull request merged**
