### PR TITLE
windowlist@cobinja.de Fix non-shwowing borders at certain panel heights

### PR DESCRIPTION
**Pull request by Cobinja**
This fixes https://github.com/linuxmint/cinnamon-spices-applets/issues/1798

### CODE REVIEW

**Comment by Cobinja** [comment]
@khatamnejad Can you confirm that this fixes it?

**Comment by Cobinja** [comment]
@germanfr Done in #1812

**Comment by khatamnejad** [comment]
Sorry @Cobinja! I am very new to Cinnamon and don't know how I could test your fix! If you could guide me on how to do the test I would be very happy to do so.

**Comment by Cobinja** [comment]
The applet files are located in $HOME/.local/share/cinnamon/applets/windowlist@cobinja.de
Clone my github repo, checkout the branch fix-borders and copy the file applet.js

**Comment by khatamnejad** [comment]
It works perfectly now; It seems #1798 is fixed.

**Pull request merged**
