### PR TITLE
batterymonitor@pdcurtis Update to version 1.2.2

### PR DESCRIPTION
**Pull request by pdcurtis**
batterymonitor@pdcurtis Version Updates

First Commit is the first major update following transition to cinnamon-spices-applets repository
 *  Add fixed audible warning at alert stage
 * Update documentation
    * In Applet
    * In README.md (2x)
     * In changelog.txt
 *  Minor tidy-up of comments and code in applet
 *  Add extra Discharging indication via border colour
 *  Move audible alert from suspendScript to applet.js
 *  Add translation support to applet.js and identify strings for translation.
 *  Add po folder to applet
 *  Create batterymonitor.pot using cinnamon-json-makepot --js po/batterymonitor.pot

Second commit updating to v1.2.2 has:

Changes following comments from @NikoKrause 
 * Changes to text strings to remove spaces from start and end of strings for translation which are replaced by fixed strings where required for formatting.
 * Some extra strings marked for translation
 * Regenerated batterymonitor.pot

 Version information harmonised with Cinnamon
 * Version 1.2.2 added to metadata.json  so it shows in 'About...'
 * Version updated to 1.2.2 in applet.js, changelog.txt and README.md removing leading v32_ from my old internal version numbering.
 * icon.png copied back into applet folder so it shows in 'About...'

### CODE REVIEW

**Comment by NikoKrause** [comment]
The translation file looks OK.
Just one little thing.
Sometimes you are using more than one whitespace before and after a word. Also you have a whitespaces at the end of whitespaces.

You can't expect, that every translator would use the same number of whitespaces.
E.g.
```
"    " + _("Wait") + "     "
```
if you really want them to be there.

**Comment by pdcurtis** [comment]
@NikoKrause Thanks for checking so comprehensively, it has brought out the value of the new system.

I think all of the single spaces are required for layout but few of the multiple ones are essential as they just pad menus to look better so one or two more or less would not matter. The example you gave is an initial value until the first cycle is completed and will never be seen in practice.

In searching for examples I have also found a couple of strings which have not been marked for translation within composite strings of text and variables. 

I think your comments here are sufficiently valuable they should go into your howto on translations so others avoid the problem.

**Can you hold the Pull for a day or two** until I have had a chance to do a more comprehensive check to see if I also need to take any spaces out of the translated strings and put them into fixed strings.

Am I correct that I can just commit and push any changes to the same branch and they are included in the Pull?

**Comment by NikoKrause** [comment]
Yes, if you create a commit in this branch and push, it will appear here in the pull request. So it's good to create for each pull request an own branch.

You can change the title of the pull request.
Just add [WIP] at the beginning of the title.
WIP = Work in progress.
This way it won't be merged.
If you are ready remove the [WIP] prefix.

**Comment by pdcurtis** [comment]
@NikoKrause Thanks, I have added the [WIP] to the title as suggested and will now be able to sort out the strings.

**Comment by pdcurtis** [comment]
@NikoKrause I have done this with two commits as the changes are not only from your comments - is this acceptable or should I squash them and do a forced push.

**Comment by NikoKrause** [comment]
I don't mind two commits in this case.

**Comment by pdcurtis** [comment]
@NikoKrause Thanks again, I will remove the [WIP] and finally go ahead

**Pull request merged**
