### PR TITLE
[redshift@marvel4u] Tooltip update with more info about Redshift state

### PR DESCRIPTION
**Pull request by Martin1887**
Tooltip update with more info about Redshift state and pot file regenerated.

Again, I only can update Spanish translation, the other translations should be updated.

@Marvel4U, are you ok with this Pull Request?

I have added a note about my contribution in README.md file. I hope that you don't mind it :-).

### CODE REVIEW

**Comment by Marvel4U** [comment]
Heyo,
yes approved. Looks very nice.
Ofc good that you added yourself in the Readme. I'd also be fine if we're something like co-authors and can both approve mergers.

**Comment by jaszhix** [comment]
It could be because I'm running Cinnamon git, but enabling this appears to hide all the applets in the far right section of my panel.

screenshot from 2017-08-14 06-28-01

I tested the version on Spices, and  it doesn't hide the other applets like this does for some reason, but the button is still stretched out. Also noticed this in glass.log:

```
info t=2017-08-14T11:21:47.242Z Error getting Cinnamon backlight power settings true,,Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown:
```

It could be my configuration, or the current state of Cinnamon on master, but I'm curious if anyone else is able to reproduce.

**Comment by Martin1887** [comment]
@jaszhix, the Glasslog error is due to brightness settings. The applet tries to communicate with Cinnamon Settings daemon and it is not running or similar (in my scenario the Cinnamon settings daemon dies when Cinnamon starts, I don't know why). This error means that changing brightness slider has no effect, but all Redshift settings work fine.

For me the version of this pull request works fine, I cannot reproduce the error that you comment.


Regards.

**Comment by jaszhix** [comment]
I spun up a Cinnamon 3.4 VM and couldn't reproduce it either. I rebuilt Cinnamon from master, and it appears to stretch the SVG icon out and overlap other applets in the panel section. I'm not sure why it does that, but manually setting the icon size:

```js
this._applet_icon.set_icon_size(24);
```
and placing that after the [```set_applet_icon_symbolic_path``` call](https://github.com/Martin1887/cinnamon-spices-applets/blob/2dd15ce8380384a256807d754dcbb35e285eb584/redshift%40marvel4u/files/redshift%40marvel4u/applet.js#L58) in ```_init``` fixes it.

**Comment by Martin1887** [comment]
The author of the applet, @Marvel4U, has approved the pull request. So, I think it should be merged since icon issue has not any relevance with this pull request.

Icon problems when the panel has different height is being dealt in the issue #1128. I think that this discussion should be continued there.


Thanks and regards.

**Comment by jaszhix** [comment]
I am suggesting it here because you know the code better than me. If I merge it now, then I will PR the fix regardless if it breaks something because it breaks the UI in Cinnamon dev.

**Comment by Martin1887** [comment]
But is this pull request what breaks the UI? Have you tried if version 2.0 of the applet does break it?

It seems really weird to me, since this pull request only has changed the tooltip text.

**Comment by jaszhix** [comment]
Where is version 2.0? Cinnamon git is always changing, I'm just trying to give a heads up. I don't blame you, you wouldn't have any way of knowing...

**Comment by Martin1887** [comment]
Version 2.0 of the applet is the previous delivered version, the master in git of the applet just before you have merged this pull request.

**Pull request merged**
