### PR TITLE
Update recorder.sh

### PR DESCRIPTION
**Pull request by Hyakki09**
This change makes it work with pipewire.

### CODE REVIEW

**Comment by rcalixte** [comment]
@Hyakki09 Have you tested this on older versions where Pipewire is not the default and therefore possibly not installed?

**Comment by Hyakki09** [comment]
> @Hyakki09 Have you tested this on older versions where Pipewire is not the default and therefore possibly not installed?

Oopps My bad, didn't test it on older version without pipewire.

**Comment by rcalixte** [comment]
> Oopps My bad, didn't test it on older version without pipewire.

It's fine. If it doesn't work. We can make two versioned folders and that will resolve the problem. It's just good to know what we need to do so that we don't break the applet for users currently using it.

**Comment by Hyakki09** [comment]
> > Oopps My bad, didn't test it on older version without pipewire.
> 
> It's fine. If it doesn't work. We can make two versioned folders and that will resolve the problem. It's just good to know what we need to do so that we don't break the applet for users currently using it.

Yes, and this makes it work with linux mint 22.

**Comment by rcalixte** [comment]
> Yes, and this makes it work with linux mint 22.

Have you had a chance to check against previous versions?

**Pull request closed without merging**
